code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
=> issue16: make EnumLiteralRef statically evaluatable

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
Fix #23 
I could not test that appropriately, sorry about that
=> issue23: fix calculation of the type of MinusExpression

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
This method was always returning false. I reimplemented it and added a few tests. All tests passed when running ./gradlew check locally
=> Correct NumberType.isSameAs

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
Created this  feature: https://github.com/IETS3/iets3.opensource/issues/76
-added the AttributesSection to the component editor
-attributes are now visible + creatable + editable directly in the section
-furthermore the attributes are still visible in the inspector too
Will look like this:
=> #76: Component: Editor: AttributesSection

build.gradle, projectlibraries.overrides.properties.example, projectlibraries.properties
-added setup task to gradle
-commited projectlibraries.overrides.properties files
=> build setup: added new gradle task

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps
LastOp should implements IOrderedCollectionOp (as FirstOp does) instead of implementing IOrderedCollection
=> LastOp implements IOrderedCollectionOp not IOrderedCollection

code/languages/org.iets3.opensource/.mps/modules.xml, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
Looks like you removed accidentially the devkit from packing in d26d5f1. 
I've added it back now.
=> build: added missing org.iets.req devkit to org.iets3.req.os plugin

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/constraints.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/intentions.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/statemachines@tests.mps
=> Kernelf statemachine improvements

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/generator/template/main@generator.mps, code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/models/core@tests.mps
If there is a default row within a multidectab, else is generated for it. The Exception that was not reachable before is not generated anymore.
=> kernelF genjava: improve generneration of multidectabs

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
=> kernelF: added NC proposal to record name in editor

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/plugin.mps
... of a binary expression, even if the left side was sufficient to decide
if it would be applicable or not. Thus TemporalOps was changed accordingly
=> The temporal interpreter did eagerly evaluated the left and right side

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.allScripts.build/models/org/iets3/opensource/allScripts/build/build.mps
This reverts commit c14e0f73d38125b1f1918c807246705b0cbcb73f, reversing
changes made to 6aaa2d6866bda9fcdca91999cf6d05a5d0a03cf8.
=> Revert "Merge pull request #196 from IETS3/feature/solver-problemview"

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.path/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.path/models/structure.mps
The PathElement checks the member to evaluate wether it should be a L-value. Implementation is similar to the DotExpression.
=> Path elements can now be L-values

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/typesystem.mps
This way custom declarations can be easily used inside of a BlockExpression.
=> Add IDeclaration interface to generalize ValExpression and LocalVarDeclExpr

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/main@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test/in/expr/os/m1@tests.mps
This PR implements reverse for lists and union/diff for sets.
It implements the actual language concepts, tests, interpreter support and Javagen support.
=> Support additional collection operations for KernelF

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/structure.mps
* Consider root nodes
* Add optional tracking of properties (non-default values are considered "visited")
=> StructuralCoverageAssQuery enhancements

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/structure.mps
DateType now implements the interface `ITypeSupportsDefaultValue`. The default is `LocalDate.MIN`.
=> kernelF: added default for DateType

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/structure.mps
All defaults are set to the beginning of the UNIX time  (1.1.1970). Default ranges are according to Type one year or one month from this 1.1.1970)
=> Default Value for all datetime range types in KernelF

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/main@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test/in/expr/os/m1@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/todo@tests.mps
I added the generator for tuple assignments and moved the corresponding Test from todo (interpreter only) to m1. Lodas requested this (Issue 564)
=> Java Generator for Tuple Assignments

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/org.iets3.core.expr.util.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.toplevel.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
- fixed interepter coverage for BuildExpressions and MultiDecisionTables
- fixed vertical line in the editor for MultiDecTabs
=> Interpreter test coverage fixes for BuildExpressions/MultiDecTabs

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/main@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps
Just a small fix in two reduction rules:
- added Cast in generated code
- changed parameter for generated function call
=> kernelF-genjava: fixed java generation for ValueAtOp

.gitignore, code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.datetime/generator/template/main@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps, code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/test.ex.core.expr.genjava.msd, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/test.in.expr.os.msd
Mixed date deltas like `1 days + 3 months + 5 years` are now legal.
=> Support for mixed date deltas

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.datetime/generator/template/org.iets3.core.expr.genjava.datetime@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps
* Date delta magnitude can be a negative number.
* Support unary negation of date delta values.
* Use grammar cells in date delta editors to better handle priority in
relation to unary minus.
=> Add support for negative date deltas

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.temporal.rt/models/runtime.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.temporal.rt/org.iets3.core.expr.genjava.temporal.rt.msd, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps
Lodas issue 775
Interpreter and generator == and != for temporals can now deal with strings.
=> kernelf: interpreter and generator for string comparison with temporals

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/solutions/playground/models/m1.mps
https://gitlab-extern.itemis.de/datev/datev-steuer/issues/101
=> Fixed Vertical Layout

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps
This PR provides fixes for coverage scope in IMultiTabDec and ConvertPrecisionNumberExpression
=> Coverage fixes

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/structure.mps
This allows building other kinds of TestCases (which are containers of TestItems), by introducing an interface named ITestItemContainer.
=> Generalize TestSuite/TestCase interaction

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/migration.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/org.iets3.core.expr.datetime.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.datetime/generator/template/org.iets3.core.expr.genjava.datetime@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps
=> added earliest/latest expressions in date

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/typesystem.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/org.iets3.core.expr.math.interpreter.msd, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/math@tests.mps
Added rat <op> real operations
=> rat <op> real now works by transforming the rat to a real

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/org.iets3.core.expr.genjava.base.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.messages/generator/template/org.iets3.core.expr.genjava.messages@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.messages/org.iets3.core.expr.genjava.messages.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/constraints.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/org.iets3.core.expr.messages.migration.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/org.iets3.core.expr.messages.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.messages.interpreter/org.iets3.core.expr.messages.interpreter.msd
- effectiveContext() in IMessageNamespace;
- replaced all usages of IMessageNamespace. content with call of effectiveContext();
=> EffectiveContext method for KernelF IMessageNamespace

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/generator/template/org.iets3.core.expr.genjava.util@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/utils@tests.mps
I am reverting the commit that removes some concepts that are still in use in iets3.
Since this change that iets3.core build is failing.
=> Add back removed concepts

build.gradle, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/todo@tests.mps
Switched MPS 2019.1.x maintenance branch to MPS 2019.1.6
=> Update build.gradle to MPS 2019.1.6

build.gradle, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/todo@tests.mps
- merged maintenance/mps20191 branch
- updated MPS version to 2019.2.4
=> Merge maintenace20191 / mps 2019.2.4

build.gradle
=> removed mbeddr branch dependency

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/generator/template/org.iets3.core.expr.genjava.util@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/org.iets3.core.expr.genjava.util.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/typesystem.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.dectabs@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/test.in.expr.os.msd
For Dectabs, typesystem, java generator and tests are implemented to support ranges with real type.
=> Dectab ranges with real

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
fix NPE when expression would yield null on renderReadable
replaced concept comparison by refrence with isSubConcept of to fix undefined behavior
and make the intend clear
=> expr.base: fix various issues in BinarExpression.requiresVerticalLayout

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/org.iets3.core.expr.typetags.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
The PR  fixes type calculation for if expression, match expression, try expression and alternative expression if units are involved.
=> issue #349: Fix type calculation for expressions with units

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/typesystem.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/math@tests.mps
* Added test cases for interpreter
* Prevent using reals in the exponent
=> Added ability to pow operations with a negative exponent

code/languages/org.iets3.opensource/languages/org.iets3.components.core/org.iets3.components.core.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.attributes/org.iets3.core.attributes.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/org.iets3.core.expr.collections.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.path/org.iets3.core.expr.path.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/org.iets3.core.expr.toplevel.mpl, code/languages/org.iets3.opensource/languages/org.iets3.req.core/org.iets3.req.core.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.collections.stubs/org.iets3.core.expr.base.collections.stubs.msd, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.functionalJava/org.iets3.core.expr.genjava.functionalJava.msd, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
cleaned up:
- empty generators
- superfluous/missing extended languagues
=> get rid of warnings in languages

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
Scopes for the Component concept may have duplicate or triple entries - this PR fixes this.
=> Fix wrong duplicate/triplicate scoping for components

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
=> comp.core: fix stack overflow in transtiveDependencies()

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.plugin/models/org/iets3/core/plugin/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.doc.plugin/models/plugin.mps
Retrieve GlobalIconManager using `GlobalIconManager#getInstance()` rather than `Application#getComponent()`.
=> Fix error about GlobalIconManager being a service, not a component

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/models/org.iets3.core.expr.simpleTypes.runtime.mps
Replace object equals() method with null-safe Objects.equals() in (Not)EqualsExpr genenerated Code.
=> Use Objects.equals() in (Not)EqualsExpr genenerated Code

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/org.iets3.core.expr.genjava.temporal@generator.mps
The missing brackets lead to cast exceptions in a customer project
=> kernelF: add brackets to generator output for valueAtOP

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
switch layout of isSome Editor from horizontal to indent
=> isSome: indent layout for neat linebreaks

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
Some minor refactorings in component port behavior in order to allow other languages to tailor port-connection checking.
=> Refactor port behavior code to improve extensibility of component language

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.tests/generator/template/org.iets3.core.expr.genjava.tests@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.records@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.records@tests.mps
Enables Applying Equals Expression to IRecordTypes
Interpreter could already handle this case, typesystem and generators are adapted with this PR
=> Bugfix kernelf records equals

build.gradle, build/scripts/build-allScripts.xml, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.allScripts.build/models/org/iets3/opensource/allScripts/build/build.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, projectlibraries.overrides.properties.example, projectlibraries.properties
This PR adds support for creating a full distribution package with all language dependencies which can be published as a github release.
=> Build full distro with Github release

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.migration.mps
=> expr.units: do not migrate extensions units

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
No actual change. Auto update of references in the build script.
=> Updated references after moving plugins from mbeddr to MPS-extension

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.migration.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
Merge branch maintenance/20193 to maintenance/20201 and run all re runnable migrations .
=> merge mps20193 to mps20201

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/math@tests.mps
What has been done:
- math sum interpreter for rational has been fixed
- tests for math interpreter extended
=> Fixed math interpreter for rationals

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
Fixes editor issue with adding EnumLiteral (#419 )
=> simplified enum literal editor

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps
Merges latest state of 2020.2 maintenance branch to master.
=> Merge maintenance/mps20202 to master

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
Merges recent changes on 2020.1 maintenance branch to 2020.3 maintenance branch.
=> Merge maintenance/mps20201 to maintenance/mps20202

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/org.iets3.core.expr.math.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/org.iets3.core.expr.toplevel.mpl, code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/org.iets3.req.plugin.msd, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
This re-adds the recently deleted actions implemented using the context actions tool from the mbeddr platform. Some projects still need them. The action implementations for the MPS context actions tool is still there.
=> re-add actions for "Context Actions 2"

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.datetime/generator/template/org.iets3.core.expr.genjava.datetime@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps
KernelF: Fix generated code for logical Less/GreaterEqualsExpression
Bug: If combined with other logical expressions, these `<=` and `>=` expressions will mix up with
the other expressions in the generated code and return a wrong value.
=> KernelF: Fix generated code for logical Less/GreaterEqualsExpression

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.stateMachineExample/sandbox/org.iets3.core.expr.genjava.stateMachineExample.sandbox.msd, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/org.iets3.core.expr.lookup.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/org.iets3.core.expr.math.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.metafunction/org.iets3.core.expr.metafunction.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/test.ex.core.expr.genjava.msd
migrations: run re-save project/ update versions in descriptors and reload modules from disk in the build scripts
=> run migrations from migration-assistant

build.gradle
Removing the publication until #493  is resolved
=> removed github packages publication

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps
- compatibility issues with previous versions if this PR introduces any
breaking changes
>> No Problems +
- hints on the included migrations and things to consider when applying
the migration to the own project
>> No MIgrations
- reference to a related Github issue
>>  #490 explains it all
=> Omit double UI-Messages in buffer for async error highlightning

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.base@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
Until now, the type system of int/int resulted in an int type. But the runtime created a real, which led to problems. I have fixed the type system to also return an real. No tests fail because of that change.
=> int / int -> real

code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.base@tests.mps
Fixed broken int / int division test
=> fixed int / int test

build.gradle
This PR adds a ghp for all artifacts:
* org.iets3.opensource
* org.iets3.opensource.tests
=> build: add github packages publication for artifacts

code/languages/org.iets3.opensource/_spreferences/PlatformTemplates/module.msd
The breadcrumb language was recently complete removed.
=> Remove breadcrumb reference

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tracing/models/editor.mps
Fix lifting of tracer results back into the editor. 
The added editors were accidentally removed in a merge in commit: a820e29773874d2b89b19ad6ec51ba1285b1d02c
=> Fix lifting of tracer results back into the editor

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
The generator works with BigInteger, the interpreter does not and as a result cast-exceptions can occur.
=> Use BigInteger in interpreter of UpToTarget

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/constraints.mps
- adds generated names to this nodes, otherwise a constraint error happens
- the name can't be null because then there is a constraint error for duplicate names ('null')
=> Fix EmptyMessageContent constraint error

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.lambda.interpreter/models/plugin.mps
- fixes empty cells in IMultiDecTab
- fixes lambda expression
- fixes short lambda expression
- ignores documentation comments
=> Minor coverage fixes

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.messages.rt/models/rt.mps
Messages can now be compared with equals and also work as keys in various collections.
=> Override equals and hashcode for Message class

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.toplevel.interpreter/models/plugin.mps
Adds coverage support for concept `EnumIsInTarget`.
=> Coverage: Fix for EnumIsInTarget

build.gradle
Updated project build to MPS 2021.1.4 (fixes several editor tests, broken after updating dependencies to the newest MPS version)
=> updated project to MPS 2021.1.4

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
The supertype calculation for the list fails because the tuple types of the first and second literal are considered as different because of the first number (100 vs. 100.4). The only common super type  is `TupleType`.
To understand the issue, let's compare the typeof implementation of the kernelF `ListLiteral` with the baselanguage `ArrayLiteral`. In the `ArrayLiteral` the element type get's calculated through an inequation statement: `infer elementType :>=: typeof(item);`. In the ListLiteral it gets calculated through a call to PTF.computerSupertype with [this](http://127.0.0.1:63320/node?ref=r%3A5bf19129-2710-45a6-906e-9ee2d0977853%28org.iets3.core.expr.simpleTypes.plugin%29%2F3237442461102096418) implementation for simple types. As a result all the other typesystem mechanics that …
=> Set cartesian product of tuple element types as super types of TupleType

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.units.si/models/units.mps
=> Units: Rename quantity metre to length

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
I've fixed #576 but also checked all other optional cells and fixed some other issues that are related to these cells. More info can be found in the commit messages.
=> Fix not working conditional editors

build.gradle
Backport of https://github.com/IETS3/iets3.opensource/pull/579.
=> Publish to artifacts.itemis.cloud

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/org.iets3.core.expr.genjava.temporal@generator.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/models/org.iets3.core.expr.temporal.runtime.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps
This is the same fix as #586, but this time for the generator and not for the interpreter.
=> Generator fix for #586 + some more tests

build.gradle
Merging all 20201 -> 20202 chnages.
=> cascading merge to align maintenance branches 

build.gradle
Merged 2020.3 changes to master.
Additionally build dependencies have been updated:
- use latest gradle plugin version before update to Gradle 7.x
- use JBR for MPS 2021.1 version
=> cascading merge to align maintenance branches (2020.3 to master)

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
The type constraint that disappears is too confusing for the user. Now it works similar to the type constraint in list literals.
=> [minor] Temporal: Make type constraint in temporal literal optional 

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps
The same change has been applied to runSolver in #644 .
I have tested the changes locally  and did not run into any breakages.
=> Make the method runSolverAsync virtual.

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
This is basically the dispose method of the tracer tool. I've reduced the command access to read access because the dispose method is somewhere called with read access and you can't elevate read access to command access. This method only access nodes and writes to the user object which apparently doesn't need write or command access.
```
Failed to dispose part class org.iets3.core.expr.plugin.plugin.DisposeDisposables_ProjectPluginPart of project plugin class org.iets3.core.expr.plugin.plugin.Plugin_ProjectPlugin
jetbrains.mps.smodel.IllegalModelAccessException: deadlock prevention: can not elevate model read to a command
at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:266)
at jetbrains.mps.smodel.ProjectModelAccess2.executeCommand(ProjectModelAccess2. …
```
=> Expr plugin: reduce command to read access in InterpreterUserObjectDecorator

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
This fixes a bug in the typesystem where equalitites of collections were not typechecked correctly.
=> Make collectiontype implement IComplexTypeSupportsEquals (#659)

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.base@tests.mps
Also include some tests to ensure that the typesystem will remain consistent.
Closes #664
=> Add a type inference rule for IfElse Section (#664)

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
Also refactor type equality for collections by reusing the isSameAs function. Add tests for map comparisons.
=> Add support for type equality to maps

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/org.iets3.core.expr.typetags.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
This uses the end cell from #657 to make it clear where the end of a tagged expression is to fix #675 .
=> Add a EndCell to tagged expressions (#675)

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
This is a follow-up to #709, rewording the error messages a bit.
=> Improve unit error messages

CHANGELOG.md, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.stringvalidation.runtime/models/org.iets3.core.expr.stringvalidation.runtime.runtime.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.stringvaliation@tests.mps
The new test cases didn't work in the past.
=> Stringvalidation: fix Runtime#findAllNumbers index calculation

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
Addresses issue: #732 
Because there is no way to override an action, we use an extension point to customize it.
=> Feature/732 introduce extension point for showTrace

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.collections@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.records@tests.mps
The returned type was not correct. We didn't see it because we didn't assign the result to variables in our tests.
=> Adjust SimpleSortOp generator to return the correct type

CHANGELOG.md, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.stringvalidation.runtime/models/org.iets3.core.expr.stringvalidation.runtime.runtime.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.stringvaliation@tests.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.stringvalidation@tests.mps
This is a follow-up of https://github.com/IETS3/iets3.opensource/pull/720. The actual error was in a different class. While the predecessor code also doesn't look right to me, the tests are passing but I've at least added some more tests to make sure that the code is working.
=> String validation: Fix wrong indices in Runtime#findAllNumbers and XExecutor successor Check

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
Addresses issue: #737
Little changes to avoid deprecated CTORs and option usages.
=> trace explorer: avoid usage of deprecated entities

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/constraints.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/structure.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/models/org.iets3.core.expr.simpleTypes.runtime.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/org.iets3.core.expr.simpleTypes.runtime.msd, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.toplevel.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.enums@tests.mps
This PR addresses issue #750 
It is fully compatible with previous versions (no breaking changes).
No migration is needed.
=> Enumerations can have an order

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.functions@tests.mps
This ticket addresses the warning and errors mentioned in #786
The generation of the according factory method or TreePVector is now done with the type parameter to avoid MeetType derivation during the generation process.
=> Added typing information within generated sources to create TreePVectors.

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.units.si/models/units.mps
=> units.si: renamed weight to mass 

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/constraints.mps
- fixes hhttps://github.com/IETS3/iets3.opensource/issues/685
- MPS 2022.2 because it is not reproducible in MPS 2021.3
- Not relevant enough for changelog.
=> Fix section marker null pointer

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/structure.mps
Make [GenericFunctionType](http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F6850639405182115289) abstract to prevent appearance on code completion menu
Closing #708
=> Make GenericFunctionType abstract

docs/CODEOWNERS
=> code owners: updated with new people

build.gradle
solves #823 fixes customer branch
=> fix customer branch matching for release

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.functions@tests.mps
=> Fixes compilation errors when using various methods on lists

build.gradle
- should fix https://github.com/IETS3/iets3.opensource/issues/905 through https://github.com/mbeddr/mps-gradle-plugin/commit/156775ab580c3d9269f052b460950a0f4d3e42c6
=> Update the mps-gradle-plugin

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
Example: number(1,3) and number[0,3)
I use the mathematical symbols for[ open and closed intervals](https://en.wikipedia.org/wiki/Interval_(mathematics)#Definitions_and_terminology).
=> Implement exclusive number ranges

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/test.in.expr.os.msd, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps
The fixed errors don't appear on older maintenance branches, therefore I am targeting `master` instead.
=> Project: fixed minor model checking errors

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/constraints.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
- The _equals_ method was missing for _EnumLiteral_.
- fixes https://github.com/IETS3/iets3.opensource/issues/886
=> implement enum equality comparison

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.components.core/org.iets3.components.core.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.base/org.iets3.core.base.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.dataflow/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.dataflow/org.iets3.core.expr.dataflow.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps
=> genjava.toplevel: Reduction rule for EnumLiterals is now also applied for sub concepts

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
=> org.iets3.core.expr.typetags.physunits: Enriching API and fixing minor issues

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.mutable.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/mutable@tests.mps
Fixes #701 
Prevent the following expression from failing 
```
fun f/RM(b: box<number>) { 
val x = b.val 
b.update(12) 
b.update from (12) to (x + 1) 
}
```
=> Fix update inequality check

build.gradle, gradle.properties, settings.gradle
Porting License-Scanning feature to older maintenance branches.
=> License-Scanning feature  for IETS3.Opensource

build.gradle
Fixes wrong group id in tests publication.
=> gradle: fixed artifactid and pom dep. of tests

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
There were some dependencies included like the tracing language which is not needed. This language is even excluded in one of our projects.
=> cleanup dependencies of the unit language

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl
=> Feature/make async solver task creator more robust #993

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl
=> Bugfix/revert changes in org.iets3.analysis.base causing solvertasks in iets3.org to fail #1026

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
The main goal was to make it possible to enter all units with the keyboard. The class _UnitNameReplacementHelper_ can also be used for generator purposes.
=> physunits: improve the code completion menu

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
=> TraceExplorer: Fix setting focus when using node mapper (#1032)

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
=> TraceExplorer: weakens too restricted interface again (#1032)

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps
TopLevelMultiDecTab and MultiDecTab are sharing an editor component. However the insert behaviour was only reflecting the TopLevelMultiDecTab concept. 
This is fixed now.
=> MultiDecTab: fixed insert behaviour

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/org.iets3.core.expr.repl.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps
This is a follow-up of https://github.com/JetBrains/MPS-extensions/pull/974. See this PR for more information.
=> Small table improvements

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/intentions.mps
=> core.expr.base: show hex attribute better in diff view

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
typical stacktrace:
```
User's action doUpdate method failed. Action: Trace: select next trace and inspect source. Class: org.iets3.core.expr.tracing.plugin.plugin.selectNextTraceNodeAndInspectSource_Action
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[SE-SearchTask-ActionSearchEverywhereContributor,4,main] 714085269 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 48450552
at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1078)
at …
```
=> fixed regularly showing error bubble in selectNextTraceNodeAndInspectSource_Action

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
It got lost in an automatic/manual merge commit
=> Restore #1097

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
Example: -255 was converted to 0x-ff before.
=> expr.base: convert negative decimal values correctly to hexadecimal values

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps, code/languages/org.iets3.opensource/solutions/test.org.iets3.analysis.base/models/test.org.iets3.analysis.base.async@tests.mps
=> Provide Env for TaskRunPhase (#1152)

build.gradle, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
Minor improvements to local Gradle builds.
=> build: improve local tests

code/languages/org.iets3.opensource/.mps/modules.xml, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os.comma/models/test.ts.expr.os.comma.m1@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os.comma/models/test.ts.expr.os.comma.plugin.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os.comma/test.ts.expr.os.comma.msd, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
The PR https://github.com/IETS3/iets3.opensource/pull/1113 somehow got lost in a merge (fixes https://github.com/IETS3/iets3.opensource/issues/1156)
=> backport: make InfHelper process comma separator

code/languages/org.iets3.opensource/solutions/test.org.iets3.analysis.base/models/test.org.iets3.analysis.base.async@tests.mps
It sometimes fails on the CI and you can't reproduce the issue locally.
=> Comment out the flaky test

code/languages/org.iets3.opensource/solutions/org.iets3.core.junit.interpreter.run.configuration/models/org.iets3.core.junit.interpreter.run.configuration.plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.junit.interpreter.run.configuration/org.iets3.core.junit.interpreter.run.configuration.msd
this addresses #1108
and the previously mentioned pull request #1109
=> fixes possible NPEs and unfound test cases

build.gradle
=> gradle: updated mps version

build/scripts/build-allScripts.xml, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
re-enable untyped columns in DataTable
Used to work before #943
=> re-enable untyped columns in DataTable

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
Fixed NPE in `CollectionTypeHelper`, related to `InfHelper` `@NotNull` annotations.
=> fixed NPE in CollectionTypeHelper

code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd
This language doesn't exist anymore.
=> remove references to removed language com.mbeddr.mpsutil.httpsupport

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/org.iets3.core.expr.math.interpreter.msd, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
- fixes https://github.com/IETS3/iets3.opensource/issues/1186
The PR https://github.com/IETS3/iets3.opensource/pull/1119 got accidentally merged into 2024.1 instead of 2023.2
=> Backport: removed math.interpreter lib folder as model folder

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps
* The status bar may be null in case of the default project ("welcome screen"). Guard against this.
* Unregister the solver task change listener when the widget is being disposed of.
Fixes #1202.
=> Fix NPE in ISolvableMonitorNotification#projectOpen

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
Without it, those two languages can't be loaded transitively.
=> add missing dependencies on the MPS context actions tool

CHANGELOG.md, build/scripts/build-allScripts.xml, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps, code/languages/org.iets3.opensource/languages/test.ts.expr.os.nix/models/test.ts.expr.os.nix.typesystem.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.allScripts.build/models/org/iets3/opensource/allScripts/build/build.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.interpreterExecutor/org.iets3.opensource.interpreterExecutor.msd, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.LeastCommonSuperType@tests.mps, code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
before, this created an error:
```
val t1 : [int, int] = if true then [1, 2] else nix 
```
because the type of `if` was _join(nix,tuple)_
=> fix for mixing nix and tuple types

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/org.iets3.core.expr.genjava.toplevel.mpl, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.toplevel.rt/models/rt.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.toplevel.rt/org.iets3.core.expr.genjava.toplevel.rt.msd, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.contracts@tests.mps
=> toplevel.rt.rt: introduced hashCode() and equals for projection results.

build.gradle
Updated sbom.json path in the published zip to avoid conflicts with other language libraries during extraction
=> updated sbom.json path in the published languages zip

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.plugin/models/org/iets3/core/plugin/plugin.mps, code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps, code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
=> Revise AnAction.getActionUpdateThread property 

CHANGELOG.md, code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/behavior.mps
- fixes https://github.com/IETS3/iets3.opensource/issues/1307
=> iets3.core.base: Add a missing null check

CHANGELOG.md, code/languages/org.iets3.opensource/.mps/modules.xml, code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.vanguard/models/org.iets3.variability.artifacts.vanguard.behavior.mps, code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.vanguard/models/org.iets3.variability.artifacts.vanguard.editor.mps, code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.vanguard/models/org.iets3.variability.artifacts.vanguard.structure.mps, code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.vanguard/org.iets3.variability.artifacts.vanguard.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
=> 1335: Rename org.iets3.variability.artifacts.base to org.iets3.variability.artifacts.vanguard

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.components.functional/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.components.toplevel.adapter/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.dataflow/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.doc/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.natlang/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.query/models/org.iets3.core.expr.query.intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.glossary/models/intentions.mps, code/languages/org.iets3.opensource/languages/org.iets3.req.core/models/intentions.mps
Updated resolve infos after rename in the platform (`com.mbeddr.mpsutil.intentions.IntentionGroupAnnotation` -> `*.GroupAnnotation`)
=> updated dirty files due to platform changes

code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.base/models/org.iets3.variability.artifacts.base.plugin.mps
=> Add mapper to arguments (#1373)

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/models/test.org.iets3.analysis.base.solvable.behavior.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/models/test.org.iets3.analysis.base.solvable.editor.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/models/test.org.iets3.analysis.base.solvable.intentions.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/models/test.org.iets3.analysis.base.solvable.plugin.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/models/test.org.iets3.analysis.base.solvable.structure.mps, code/languages/org.iets3.opensource/languages/test.org.iets3.analysis.base.solvable/test.org.iets3.analysis.base.solvable.mpl, code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps, code/languages/org.iets3.opensource/tests/test.org.iets3.analysis.base/models/test.org.iets3.analysis.base.highlighter@tests.mps, code/languages/org.iets3.opensource/tests/test.org.iets3.analysis.base/models/test.org.iets3.analysis.base.uisolvable.mps, code/languages/org.iets3.opensource/tests/test.org.iets3.analysis.base/test.org.iets3.analysis.base.msd
=> Feature/ease the testing of error highlightning of i solvable #1386

build.gradle, settings.gradle
Makes the build compatible with Gradle 9.
Fixes #1269
=> make build gradle 9 compatible
