IETS3/iets3.opensource

build.gradle
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
opensource.iml

The exact build number for IETS is now shown in Plugins screens of MPS:
- Replaced static version number `1.0` in MPS build scripts with new `version` variable
- Pass build number from gradle into ant as `version`which is then put into the plugin.xml
The resulting plugin XML looks like this:
```<idea-plugin version="2">
<id>org.iets3.comp.os</id>
<name>org.iets3.comp.os</name>
<version>
refactor-buildnumber-in-plugin-version.0.1.1748.gd0bb943
</version>
<depends>jetbrains.mps.core</depends>
<depends>org.iets3.core.os</depends>
<depends>org.iets3.req.os</depends>
<extensions defaultExtensionNs="com.intellij">
<mps.LanguageLibrary dir="/languages"/>
</extensions>
</idea-plugin>```

build: version number in plugin.xml

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/constraints.mps

Currently this constraint forbid the use of parameters in components of kind hardwarekind. Because hardware components only allow elements of which are flagged with a hardware specific kind. 
**Problem:** 
If a parameter implements IKindspecific, it still cannot be defined for a hardware or|and functional kind, because parameters are on iets3.os and do not know anything about other kinds. 
With this adaptions parameters would be usable in functional kinds (as before) and in all hardware components. The usablity would be identical for both cases.

Refactor Parameter: Parameters should be used in hardware and functional kinds

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.path/models/typesystem.mps

Currently map return a list only when invoked on list, otherwise it returns a collection. This is an issue when using it with an OrderedCollection which is not a list. I think also in that case it should return a list.
PathElement instead returns always a collection. I think that if it is invoked on something ordered it should return a list.
I would return lists because I need to return a collection that is ordered so I think List satisfies these requirements.

Make map and pathElement work with OrderedCollections

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

Fix #92
Currently a number with decimal digits is assignable to number{inf} while an integer number is not.

Issue 92: Making an integer constant assignable to number{inf}

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/constraints.mps

In the constraint aspect of the Component concept: 
http://127.0.0.1:63320/node?ref=r%3Aa9d6b037-1504-40b0-9d90-6aed1da43430%28org.iets3.components.core.constraints%29%2F7126186526844781745&project=org.iets3.opensource
**a can be parent** constraint is implemented to restrict the creation of several component substructures inside a component. 
Unfortunatelly the constraint is limited to the concept `ComponentInterface` and not `AbstractComponentInterface`. Because of this the constraint is not working inside of hardware components.
This fix generalizes the check to work on `AbstractComponentInterface`.

Generalized component constraint

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/migration.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/org.iets3.components.core.mpl
code/languages/org.iets3.opensource/languages/org.iets3.components.plugin/org.iets3.components.plugin.msd
code/languages/org.iets3.opensource/languages/org.iets3.components.req/org.iets3.components.req.mpl
code/languages/org.iets3.opensource/languages/test.iest3.component.attribute/test.iest3.component.attribute.mpl
code/languages/org.iets3.opensource/solutions/test.iets3.core.assessment/test.iets3.core.tracequery.msd
code/languages/org.iets3.opensource/solutions/test.ts.components.core/models/tests@tests.mps
code/languages/org.iets3.opensource/solutions/test.ts.components.core/test.ts.components.core.msd

comp: introduce base concept for all kind of connectors  …
In order to allow a more abstract representation of connectors for a new
connector `AbstractConnectorBase` was introduced. This concept assumes
that at least a source port (governing port) exists. The target for this
connector is still a abstract node. It is usefull in cases where a the
target of the connection is a bus or some other target that is not a port.
In additon the `AbstractConnector` was renamed to `AbstractPortToPortConnector`
It is a specialisation of the `AbstractConnectorBase` which asumes a that
the connection is made between two ports. Most of the behaviour methods
and interface implementations have been moved up to `AbstractConnectorBase`.
The `AbstractConnectorRefTarget` was changed to point to a …

Add AbstractConnectorBase as common super concept for all connectors

---

build.gradle
build/iets3.opensource.allScripts/build-allScripts.xml
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.allScripts.build/models/org/iets3/opensource/allScripts/build/build.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.allScripts.build/org.iets3.opensource.allScripts.build.msd

We don't need to depend on the allScripts artefact of the upstream dependency we can simply depend on the "normal" build solution to simplify our dependencies.

build: remove dependency on mbeddr.platform allScripts

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/test.iest3.component.attribute/models/behavior.mps
code/languages/org.iets3.opensource/languages/test.iest3.component.attribute/models/editor.mps
code/languages/org.iets3.opensource/languages/test.iest3.component.attribute/models/structure.mps
code/languages/org.iets3.opensource/languages/test.iest3.component.attribute/test.iest3.component.attribute.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/solutions/test.ts.components.core/models/tests@tests.mps
code/languages/org.iets3.opensource/solutions/test.ts.components.core/test.ts.components.core.msd
doc/design/01-kindaware-scope.md

Assume you have the following model: 
```
kindA component A_Comp1 {
--------------------substructure--------------------
instance [ B_Comp and A_Comp2 are in scope ]
}
kindA component A_Comp2 {}
kindB component B_Comp {}
```
Currently when you create a component instance inside of a component substructure, every component regardless of its kind is in scope. There is only a generic error message that indicates that an instance where the kind is not the same as the parent component kind can not be used.
There is currently no possibility to restrict this scope.
Customer language should be able to decide if “additional” constraints should be applied to restrict the scope of such component refs.

Allow kind aware scope calculation of Component Instances

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/typesystem.mps
doc/design/02-ports-with-dependencies.md

Includes a new port type that can wrap a IPortType. It can reference a parameter. When using these ports in connectors the type system ensures that only ports with same payload and configuration can be connected.
I removed the for "is statically evaluatable" from the checking rule of a component instance. Since that property of an expression in not maintained at all it will produce a lot of false positives.
This PR doesn't contain any of the static checking of the values. It is only the type system to specify the dependency from the port to the parameter.
WIP:

comp: add parameter dependencies for ports

---

build.gradle

Some how we must have missed to update to the latest minor versions of mps for quite a while. Using latest stable release now.

build: use mps 2017.3.5

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/constraints.mps

Now delegate connector is available for any kind of connectors, not only the ones that imply a direction. In practice this means they are available for both hardware and software connectors.
Further constraints should be implemented on downstream projects depending on the domain requirements.

delegate connectors refactoring

---

build.gradle

Simplified some of the parts of the builds scripts. Added a variable where people can simply put the mbeddr branch name they would like to build against. The script will take care of escaping the name etc. 
Also replaced some `println` with `logger.log` calls. 
Added the github release plugin to be able to push releases to github automatically.

build scripts

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This requires mbeddr/mbeddr.core#1894 to be merged. 
I removed the the dependency on the complete mbeddr mpsutil plugin and replaced it with dependencies on:
- com.mbeddr.mpsutil.interpreter
- com.mbeddr.mpsutil.varscope
- de.itemis.mps.editor.diagram
- com.mbeddr.mpsutil.contextactions
Downstream project might observe changes in there dependencies through that and are required to add explicit dependencies to their plugins to compensate as they no longer get all of msutil transitively.

reduce dependency surface

---

code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/editor.mps
code/languages/org.iets3.opensource/solutions/test.org.iets3.core.comments/models/tests@tests.mps

detaching the node in applyCommentsToIDocumentable would sometime cause:
```
java.lang.Throwable
at jetbrains.mps.nodeEditor.updater.UpdateInfoNode$UpdateInfoNodeAttribute.lambda$validateBeforeReplace$1(UpdateInfoNode.java:180)
at java.util.Optional.ifPresent(Optional.java:159)
at jetbrains.mps.nodeEditor.updater.UpdateInfoNode$UpdateInfoNodeAttribute.validateBeforeReplace(UpdateInfoNode.java:177)
at jetbrains.mps.nodeEditor.updater.UpdateInfoNode.replace(UpdateInfoNode.java:77)
at jetbrains.mps.nodeEditor.updater.UpdateInfoNode$UpdateInfoNodeAttribute.replace(UpdateInfoNode.java:143)
at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.reuseChildInfo(UpdateSessionImpl.java:349)
at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:248)
at …
```

core.base: do not detach the node the comment is applied to

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/intentions.mps

The feature makes the makeTypeRef intention of IReferencableType configurable by checking whether the Type ReferenceType is applicable for a node.

make makeRefType intention configurable by implmenting isApplicable

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Complete MPS util wasn't required as a dependency on the treenotation
was.

build: core.os remove mpsutil dependency

---

build.gradle
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

- using mbeddr with version 1.1+ which was introduced during the grammar cells migration 
- reloaded build scripts to reflect the dependency changes

build: updated to latest mbeddr platform

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/org.iets3.core.expr.lookup.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/org.iets3.core.expr.messages.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/org.iets3.core.expr.util.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Fixed a bunch of model checking errors in kernelf. Most notably some missing behaviour methods. 
Most implementations where straight forward but at least for `GenericErrorType` someone should take a look. I'm not sure why this implements a wrapper type interface even if the types doesn't wrap anything.

fixed some kernelf errors

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/org.iets3.opensource.build.msd

This is required to fix the new model checking errors introduced with the update to MPS 2018.3. 
It seems that it's no a bug in the build language but a problem with the model checker that is now becoming visible because of changes in how model checking errors are reported.

build: add dependency to mps.extensions build module t

---

build.gradle

- this eases to use the locally published version
- it also logs which mbeddr version is used

build.gradle announces exact version on local builds

---

build.gradle

The mentioned change enables the feature: `mps.generator.skipUnmodifiedModels` by default. 
This change reduces the local build time for the command line build extreamly because only the modified models are build locally and not all models/modules by default.

build.gradle: enabled incremental build for languages

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps

The rendering of ParameterValues was accidentally removed in commit: 5fa5803
This change enables the rendering again.

iets3.component.core: enabled rendering of ParameterValues in diagram

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.adt.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.dataflow.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.lambda.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.lookup.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.mutable.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.path.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.process.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.repl.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.statemachines.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tests.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.toplevel.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.util.interpreter/models/plugin.mps

Peter is dead, long live Preter :-)
This is just a proper renaming of all interpreters. It is sometimes annoying if names are spelled wrong, esp. when somebody is trying to find it with Cmd-N or full-text search.

Rename all ...Interpeter to ...Interpreter.

---

build/iets3.opensource.allScripts/build-allScripts.xml
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel.main@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.toplevel.interpreter/models/plugin.mps

This PR introduces ITypeable interface concept. ITypeable doesn't have any children, only `type()` behavior method. ITyped implements `type()` by returning `this.type`.
IRecordMember now implements ITypeable instead of ITyped. RecordMember continues to implement ITyped.
It's motivated by the need to have custom record members whose base type and multiplicity is specified separately, so the actual member type is then either the base type or collection of base type.
Although simple, this is potentially breaking change if you have defined custom IRecordMembers or are working with the IRecordMember interface so I'd like to have it reviewed before merging.

Introduce ITypeable interface concept

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/main@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.simpleTypes.rt/models/org.iets3.core.expr.genjava.simpleTypes.rt.rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test/in/expr/os/m1@tests.mps

This PR adds a parseInteger dot target to KernelF. Use it like this: `"123".parseInteger`.
It contains the actual concept, test cases and the Java generator part.

Add parseInteger dot target for KernelF strings

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps

Added margin-bottom of 3 to Row and Column Headers of DecTabs in order to improve visibility of error markers.

#437: Added margin-bottom to DecTab Column and Row Headers in order improve visibility of Error Markers

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/constraints.mps

RMRIC can now only appear in a contract item, not anywhere inside an
IRecordDeclaration.

RecordMemberRefInConstraint: tighten the "can be child constraint"

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

Extended the KernelF type system to allow equality between parameterized types like Lists, which would not be possible with Overloaded Operation Containers.
Test cases can be found in
http://127.0.0.1:63320/node?ref=r%3A75f6a9e9-cf21-495f-b1aa-7fd992d0d7d0%28test.ts.expr.os.m1%40tests%29%2F871690368833936467
from which it should be possible to deduce what the type system is supposed to do here.

Extension to KernelF's TypeSystem: Allow Equality for Lists

---

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps

Switching between test execution with generator and interpreter already worked within iets3.opensource. It worked as well for depending projects, when iets3.opensource was opened in mps together with the depending project.
Changing the Module access from hardcoded to calculated makes it now also work for depending projects when iets3.opensource is only available through artifacts.

enable switching between generator/interpreter test execution in depending projects

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel.main@generator.mps

I added a `fromValue(...)` method to the Java Code that is Generated for EnumDeclarations in KernelF. This was a customer request. There are no additional language constructs for this, because it is only needed for the code that uses the generated code.
The Generated code was already reviewed by the IT of the customer.
Only one reduction rule was changed, so this is pretty quick to review.

KernelF GenJava: FromValue Method in Generated Code of EnumDeclarations

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/main@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.messages/generator/template/main@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/org.iets3.core.expr.messages.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.base.rt/models/rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.messages.rt/models/rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.messages.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/models/messages@tests.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/messages@tests.mps

* Deprecate MessageTarget.messagValue. All calls to messages now return the full message object. If only text is desired, `.text` can be used. This encourages using the full message object in constraints so that error kind is not lost.
* Add warningID to WarningKind.
* Message: collect fqnames of members that were mentioned in the constraint in affectedMemberNames.
* Message: add userData to allow customer-specific data to be attached to the message (in the generator).

Updates to messages

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/test.ex.core.expr.genjava/models/messages@tests.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/todo@tests.mps

Fix a small issue in the interpreter for FailExpr, making it possible to use with message values.
Make sure this is caught by tests: adjust `confail` to report any exception that's not a constraint failure as an error.

Fix interpreter for FailExpr, add test

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.contracts/generator/template/org.iets3.core.expr.genjava.contracts@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.datetime/generator/template/org.iets3.core.expr.genjava.datetime@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.messages/generator/template/org.iets3.core.expr.genjava.messages@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.stateMachineExample/generator/template/main@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/org.iets3.core.expr.genjava.temporal@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.tests/generator/template/org.iets3.core.expr.genjava.tests@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/generator/template/org.iets3.core.expr.genjava.util@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/org.iets3.core.expr.genjava.util.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Since it is annoying to find the right KernelF generators to import in the model properties when they are all named `main@generator`, I renamed all KernelF java generators.

Rename KernelF Generators

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps

This PR includes support of handling collections with numbers when executing asserts in test suites. Before EqualsTestOp in the assert only took care of comparing BigInteger and BigDecimal objects by wrapping BigInteger into BigDecimal and using corresponding `compareTo()` method in BigDecimal (instead of `equals()` method which could not handle BigInteger/BigDecimal). However in case of collections it simply delegated to the `equals()` method and therefore never correctly handled numbers in the collections, which could be semantically equal, but not according to the strict equals() implementation. For example:
```
val fraction = list(1 / 4)                                                                               
test case divide [fail] { …
```

Proper support of collections in test asserts

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/org.iets3.core.expr.base.mpl

The current implementation returns the BooleanType from base language, clearly an oversight.

typeof_BinaryExpression: return the right BooleanType

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps

Implement abstract methods that get invoked when an instance of
BuilderAdapter gets created by the editor even though it is abstract.

BuilderAdapter: avoid exceptions in the editor

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps

If a field implements ITypeable (they usually do) use its type() method
to avoid invoking the type system. The type system sometimes returns
null for a node type when called from a checking rule, causing
RecordTypeAdapter to treat all fields as mandatory, including optional
ones.

RecordTypeAdapter: avoid invalid type checker errors

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

Removed a debug print from KernelF 'BangOp' editor ([Node](http://127.0.0.1:63320/node?ref=r%3A8405f486-53b5-4fe6-af3e-7f68358bd631%28org.iets3.core.expr.base.editor%29%2F2390066428848653913))

kernelf: remeoved debug print from BangOp editor

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps

Fixes broken references in ToleranceExpr due to a refactoring of the PTF class.

KernelF: fix toloeranceExpr typesystem broken PTF references

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

MultiDecTabs can have empty conditions, which is the default. It does not make sense to have multiple defaults. This is now checked and an error appears if there are multiple empty conditions.

kernelF: Error when MultiDecTab has multiple empty Conditions

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

ErrorType was not taken into account during the inference of the Binary Expression Type, which lead to errors when BinaryExpressions were used together with units.
Fix: Test operationType not only for null but also for Runtime ErrorType to get the right error messages.

take RuntimeErrorType into account when inferring type of BinaryExpression

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/editor.mps

This commit fixes the editing behavior of tagged literals
in two different cases:
* 10C + 20C : if one tried to delete the C tag, one had
to hit backspace 3 more times to delete the intermediate
artifacts
* 10: if one hit C after the 10, the cursor got placed
after the 10 and not after the C

Fix Tagged Literals Editor

---

build.gradle

Due to the 32k command-line length restriction on Windows, the junit process currently cannot be forked even with the shortest possible path of the checkout directory and fails with an error like:
```
O:\build\iets3.opensource.tests\build.xml:2133: Process fork failed.
```
I have found a workaround that seems to work reliably. See https://youtrack.jetbrains.com/issue/MPS-24137 for details. This PR integrates this workaround into the generated ant xml for tests execution.

workaround for too long command-line for junit process on Windows

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

since MPS 2019.3 "copy resources" in build "java oprions" must be true
in order to copy any resources from the module to the packaged jar

insure icons are properly copied into the distro

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/intentions.mps

In case the type could not get calculated correctly e.g. because of an
incomplete AST the intentions would throw a node case exception in their
isApplicable function rendering the complete intentions subsystem
unusable.

expr.core: fix node cast exception in wrapWith

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/org.iets3.core.expr.data.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.data.interpreter/models/org.iets3.core.expr.data.interpreter.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.data.interpreter/org.iets3.core.expr.data.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.datatable@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

New lookUp operation allowed on data tables. The operation
will look up the row based on the column and value provided
to the expression.
New flag "allows lookup" on data tables which is at the
moment only a flag to allow the operation. If the flag is
present the type system provides an info message about the
uniqueness requirements for values in a column. Right now no
static checks for uniqueness of all values in a column exists.
Since each cell can contain an arbitrary expression we would
need to run the interpreter in the checking rule to find
duplicate values.

expr.data: allow lookups in data tables

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps

Objects returned by the extensions have transient nature: they may become obsolete as soon as a module reloading event happens. It is not recommended to e.g. cache these objects. Instead is it better to get a fresh copy each time.
(https://www.jetbrains.com/help/mps/extension-support.html)
This fixes #315.

Fix caching of PrimitiveTypeMapper

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps

The BracketOP editor worked with any IOrderedCollection, but the typesystem would fail with a runtime error if it wasn't a list. To fix the typesystem rule IOrderedCollection is now inheriting from ICollectionType. Since ICollectionType extends IHasBaseType, we can use getBaseType() to fix the typesystem rule.
This replaces #257

Fix BracketOP for IOrderedCollection

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

The PR fixes a typesystem error, which was shown if min and max expressions are used with units.
I added a condition that to typeof_AbstractMinMaxExpressions that unwraps a IInterpreterWrappedExpression before checking whether the type is a real type, i.e., for units it is now checked that the inner type is a real.

[issue #366] min and max expression can now used together with units

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.records@tests.mps

Number equality in KernelF ignores zeroes after the decimal point, so 1
== 1.0. This did not hold true for records containing numbers, however,
so Point{1,2} was different from Point{1.0,2.0}.
This commit fixes the generator and the interpreter so that Point{1,2}
now compares equal to Point{1.0,2.0}.

Record equality now uses KernelF number equality

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/typesystem.mps

Two inference rules use behavior methods to infer types. But these behavior methods use the typesystem themselves (`.type:Type`) which leads to exceptions, since `.type` provides an intermediate type when the calculation is not finished.
If there is a better solution to solve this problem I am eager to see it.

expr.util: Fix cast exception for typesystem

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/behavior.mps

Adding itself to the list of visited dependencies can cause a stack over flow in
case a cycle between types exists

fix soe in transitive dependencies

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/org.iets3.core.expr.genjava.temporal@generator.mps

Parentheses are needed to prevent ambiguity when translating long dot chains. Otherwise this code:
enumTT.valueAt(time).value
was translated to:
(SomeEnum) (TemporalValue) enumTT.valueAt(inkr).getValue()
And although the AST was correct the generated code was not since casts
have lower precedence than dots.

genjava.temporal: parenthesize casts in generator templates

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/generator/template/org.iets3.core.expr.genjava.util@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.util/org.iets3.core.expr.genjava.util.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/org.iets3.core.expr.util.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.util.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.util.interpreter/org.iets3.core.expr.util.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.dectabs@tests.mps

IValidOtherwiseContainer can now give a custom type to
OtherwiseLiterals that it contains.
IValidOtherwiseContainer API was modified to handle otherwise
literals in different roles.

Decision tables now support 'otherwise' in row/column headers

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.messages.rt/models/rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

- BuilderAdapter method missingSetters() is now virtual
- org.iets3.core.expr.genjava.messages.rt.rt.Message now implements Serializable

kernelf: small adaptions

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.numbers@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

- Real values in number literals now allows for expressions such as 3e5 or 4e-4 (without specifying a dot in the left part)
- The precision computed from the string now take magnitude into consideration
- Using values such as `1.00e-11` previously caused it to become zero with java generated expressions, because the computed type had a precision of 6 in this example (6 chars after '.'). The generated code for such number was `new BigDecimal("1.00E-11").setScale(6, RoundingMode.DOWN)`.

Fix #390 : Accurate matching and precision for number literals with scientific notation

---

code/languages/org.iets3.opensource/_spreferences/TestExecutionPreferences/models/org.iets3.opensource.__spreferences.TestExecutionPreferences.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.temporal@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

The typesystem of ShortLambdaExpression was not able to handle TemporalTypes. This is fixed with this PR. Now the behaviour of the ShortLambdaExpression typesystem is the same as the one of LambdaExpression in this case.

fix kernelf shortlambda typesystem

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.collections@tests.mps

Generating a expression like `list.first(5).last(2)` lead to a cast exception due to a mix of `PVector`s and `TreePVector`s in the generated code. This is fixed with this PR.

kernelf: fix firstN, lanstN cast exception in Generator

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps

The current `STF` helper class finds a `SolverTaskFactory` based on a node's concept. However, it cannot find a `SolverTaskFactory` for a base concept of that node's concept or for an interface implemented by the node's concept.
This PR  generalizes the `STF` class in order to do a breadth-first search on the direct super-concepts (and interfaces) of a concept. It starts with the actual node's concept and moves up the hierarchy until it finds a `SolverTaskFactory`. There is also a cycle check in order to avoid infinite loops.

Generalize solver task factory: Find factory also for super-concepts

---

code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/typesystem.mps

The interface `ICanRunCheckManually` provides a checking rule which converts check results (e.g., from a Z3 solver run) into MPS typesystem errors and warnings. The check results to be converted have to implement the `IResult` interface.
This PR introduces a new interface `IHasSubResults` which can be used to attach additional results to an `IResult`. Via the behavior method `ICanRunCheckManually.showSubResults` (default: false) the subresults of an `IResult` can be converted to MPS typesystem errors and warnings during the conversion of the actual result (aka *main* result).
The sub-results mechanism is already being used by the Z3 solver integration of iets3.core, but there was no possibility to show more than one result in an editor up to now.

Allow solver check to optionally show subresults

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.plugin/models/org/iets3/core/plugin/plugin.mps

Action `runManuallyOnNode` executes an `ICanRunCheckManually` node and updates the editor afterwards. The UI updating only worked if the `ICanRunCheckManually` is the root node of the editor to be updated.
With this PR, this also works if the `ICanRunCheckManually` is a node attribute attached to the root node.
The PR also resolves some minor typos and removes debug outputs.

Fix bug in editor update after solver has been executed

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.migration.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.units.si/models/units.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

A bug in the units migration didn't set the now deprecated "description" property to null therefor
every execution of the rerunable migration would create new quantities. The migration was updated
to detect this case properly and not change the model in this case. In addition the migration now
sets the deprecated property to null.
fixes #423

Units: make units migration rerunable

---

build.gradle
listMergedPRs.sh

This PR adds automatic listing of merged PR commits since last nightly github release (tagged with `nightly-`) to the release notes of the github release.

extended nightly release notes with a list of merged PR commits

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Replaced `nodesIncludingImported` and `where( x.InstanceOf)` combination
with a direct call to `SModelOperations.nodesIncludingImported` in the
TestSuite scope implementation. This change allows MPS to cache the model
and concept tuple and improves scoping performance significant. In one
project it reduced the model checking time by 30%.
MPS doesn't support passing an expression to the concept part of
nodesIncludingImported but only allows direct references to concepts and
calling the underlying API directly was required.

expr.test: improve scoping performance

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/structure.mps

- On assert-that test cases, there is the option `go to constraint`. This was broken and is fixed  for all cases in which a constraint fail leads to a failing interpreter test
- `enum-literal.isIn()` lead to an exception, because an empty `IsInTarget`  could not be processed. The case that the `IsInTarget` is empty is now handled. In addition, an empty `IsInTarget` is not allowed anymore, because it is not meaningful
- The type inference os the `IntervalsOp` now returns a list<DateType> instead of a list<NumberType> which is
consistent with the interpreter.
This PR does not contain breaking changes

small fixes in KernelF

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.migration.mps

no breaking changes, just a fix to not migrate concept instances that are extending the unit concept.

expr.units: do not migrate extensions units

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/org.iets3.core.expr.genjava.toplevel.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.collections@tests.mps

A call on `first`/`last` on an empty list resulted in a thrown exception. Because the typesystem already handles these cases with `Optional`, the interpreter and generator now also return `none` in these cases, without an exception

KernelF: Change list.first/last, so they return none when list is empty

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/org.iets3.core.expr.math.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/org.iets3.core.expr.toplevel.mpl
code/languages/org.iets3.opensource/languages/org.iets3.req.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.req.core/org.iets3.req.core.mpl
code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/org.iets3.req.plugin.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This moves the actions from the "Context Actions 2" to the "Context Actions" tool window. The goal is to remove the "Context Actions 2" tool from the mbeddr platform.
The actions after the migration are not identical to the ones before the migration. Some were just removed, that don't appear to be useful and are not worth the effort to reimplement them.

Migration of the context actions to the MPS context actions

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

To fix build script errors, org.iets3.core.os now depends on jetbrains.mps.testing and de.q60.shadowmodels.

Fix build script

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps

This PR merges several minor adjustements/fixes for datev-steuer project to 2020.1 maintenance branch:
- proper substitute menu implemented for InlineRecords
- editor for DataIsInTarget adjusted for single argument case
- paragraph symbol allowed in record members
- NixSupport provides 3-arguments constructor
- fixed missing subst menu for custom error cell on abstract expressions

Merge datev-staging to 2020.1 maintenancne

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

Fix EmptyValue editor, so specification of a type for the EmptyValue is possible again
Bug: On creation of an EmptyValue instance the cursor is positioned at "empt|y" and cannot move to "empty|",
thus it's not possible to add a type to the EmptyValue. Going to the right results in a jump to the next cell

Fix EmptyValue editor, so specification of a type is possible again

---

code/languages/org.iets3.opensource/.mps/modules.xml
code/languages/org.iets3.opensource/devkits/org.iets3.core.expr.genjava.core.devkit/org.iets3.core.expr.genjava.core.devkit.devkit
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/org.iets3.core.expr.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/org.iets3.core.expr.genjava.base.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/org.iets3.core.expr.base.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/org.iets3.core.expr.base.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.shared.runtime/models/org.iets3.core.expr.base.shared.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.shared.runtime/org.iets3.core.expr.base.shared.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/org.iets3.core.expr.collections.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/org.iets3.core.expr.datetime.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/org.iets3.core.expr.math.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/org.iets3.core.expr.simpleTypes.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/models/org.iets3.core.expr.simpleTypes.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/org.iets3.core.expr.simpleTypes.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Terms used:
* _base runtime_: solution `org.iets3.core.expr.base.runtime`
* _shared runtime_: solution `org.iets3.core.expr.base.shared.runtime`
The new shared runtime contains classes that will be used both from the generated code and by the interpreter or in-MPS code.
Even though the individual classes used by the generated code do not depend on MPS-specific classes, extracting them from the base runtime means that the generated code no longer needs to depend on a module that contain MPS-specific code (e.g. NixSupport with its usage of the node<> type).
The base runtime was taken out of module dependencies of other runtimes.
Breaking change: class INixValue was moved from the base runtime to the shared one so references to it will need to be updated (Ctrl+R to import …

[breaking] Extract shared runtime from base runtime to reduce runtime dependencies

---

code/languages/org.iets3.opensource/.mps/modules.xml
code/languages/org.iets3.opensource/devkits/org.iets3.core.expr.genjava.core.devkit/org.iets3.core.expr.genjava.core.devkit.devkit
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/org.iets3.core.expr.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/org.iets3.core.expr.genjava.base.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/org.iets3.core.expr.base.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/org.iets3.core.expr.base.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.shared.runtime/models/org.iets3.core.expr.base.shared.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.shared.runtime/org.iets3.core.expr.base.shared.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/org.iets3.core.expr.collections.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/org.iets3.core.expr.datetime.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/org.iets3.core.expr.math.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/org.iets3.core.expr.simpleTypes.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/models/org.iets3.core.expr.simpleTypes.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.runtime/org.iets3.core.expr.simpleTypes.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/models/org.iets3.core.expr.temporal.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/org.iets3.core.expr.temporal.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Instances of collections and closures language in temporal runtime were rewritten using plain Java, to remove the dependency on MPS collections and closures runtimes.
Breaking changes:
* `TemporalValue#slices()` no longer returns a base language collection but a `java.util.List` so the collection language operations like `add` or `sortBy` are not applicable to it anymore.
* `TemporalValue#intervals()` likewise.

[breaking] Temporal runtime no longer depends on MPS collections and closures

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.dataflow/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.opensource.build.gentests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.req.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

In the last MPS version (2020.2) there was a change that impacted how nodes are converted to strings ([MPS-32042](https://youtrack.jetbrains.com/issue/MPS-32042)). Due to this change for some nodes the string+node concatenation could produce different result not readable from the user point of view (contains `(instance of <concept>)` instead of custom node presentation). To fix this, we need to always use node.getPresentation() explicitly in such cases. This PR adds required calls for all cases of previously implicit conversion of nodes to string.

Explicitly use node.getPresentation for string conversion

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.alt@tests.mps

Bug: When an `AlternativesExpression` is used with a `BlockExpression` in its `AltOption`, the generator always generates `return 5;`.
Bugfix: Add a node macro to use the specified `BlockExpression` as actual generation result.

Fix wrong generation for AltOption with BlockExpression.

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps

This PR extends the solvable monitor widget with the ability to navigate on mouse click to the ISolvable node behind the solver task to show it in the editor. This is especially helpful in case of many tasks shown in the monitor widget.

added navigation support to solvable node from monitor (#463)

---

build.gradle

This PR adds a publication to github packages for all artifacts.
In case we are building from CI and running on master/maintenance or a "mps" branch , TC will deploy all corresponding artifacts to github pages in addition to the nexus repository.
I've taken some inspiration from the PR provided for the mbeddr.platform publication: https://github.com/mbeddr/mbeddr.core/pull/2180

build: added publication to github packages

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.collections@tests.mps

Resolves #402 
As mentioned in #394, the code generated for `list.firstN/lastN(n)` caused an IndexOutOfBoundsException when `n` was greater than the size of `list`.
With this change, the original list is returned instead in such cases, aligning the semantics of firstN/lastN in the generator with the semantics from the interpreter.
Also, this makes sure `list` is evaluated only once in the generated code for each firstN/lastN instead of up to 4 times, which might matter when `list` is a complex expression.

fix firstN/lastN semantics for N greater than list

---

build.gradle

It seems like TC is not able to deploy our artifacts to github packages. 
The reason for this might be the artifactID of our `allScripts` artifact. It seems like the maven repositories on ghp do not support upper case IDs.
This PR removes the publication for the `allScript` artefact. This artefact is not really required, because all of its content is already part of the overall [org.iets3.opensource](https://projects.itemis.de/nexus/content/repositories/mbeddr/org/iets3/opensource/) artefact.
~~This PR sets the corresponding IDs to lower case.~~
~~However I am not etirely sure if this will somehow break the backwards compatibility, in case users rely on the initiall artifact ID. 
Maybe @sergej-koscejev might know?~~
FIxes #493

[breaking] publication: cleanup artifact publications

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.simpleTypes.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/operatorgroup@tests.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.nix@tests.mps

This PR fixes two inconsistencies in the interpreter for the following binary operators:
- logical and (`&&`): the special logic for short-circuit-handling was non-symmetric and different from the interpreter for `||`, adapted it
- equality (`==`): the implemented logic was different from the one for non-equality, adapted it
Regarding the short-circuit-logic for `&&` and `||`: I am not sure if this is generic enough, I had some problems implementing ternary logic using this. But as I don't know how other NixHandlers (from customer projects) are using this, I couldn't come up with a better proposal. This is maybe something for a different PR.

Fix two inconsistencies with Nix-handling in interpreter

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps

Remove duplicated auto-completion entries for `EnumDeclaration.qualified` flag and `type` option, when declaring enums and on side-transformations.

Remove duplicate node substitute action for EnumDeclaration

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/intentions.mps
code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/org.iets3.core.expr.math.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl

Pressing backspace in solver timeout removes the whole timeout part of the editor. This commit fixes this issue.

Only allow backspace in some parts of SolverControl

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

It is possible to add a unit to a TypeDef. When such a TypeDef is used (TypeDefType) it is again possible to add a unit to the TypeDefType. Especially for units, this does not make sense, so this PR fixes the problem. We don't consider all possible tags with this fix, but only units, because there might be use cases for nesting other tags.

typedefs with units

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.simpleTypes.rt/models/org.iets3.core.expr.genjava.simpleTypes.rt.rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.simpleTypes.rt/org.iets3.core.expr.genjava.simpleTypes.rt.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Improve generator for sumOp to consider the collection base type
Problem: The generator of sumOp always returned the result as a BigDecimal,
which is not obvious and a different behaviour compared to the interpreter.
Solution: The generator considers the collection base type. In case it's a NumberType,
it depends on the numbers precision whether the result will be a BigInteger or BigDecimal.

Improve generator for sumOp to consider the collection base type

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps

This pull request fixes cases where collection operations fall back to the Object type when calling collect(Collectors.toList()) in the generator and the original type is not available.
Example: Some operations (distinct, lastN) return list&lt;Object&gt; instead of list&lt;Days&gt; and cast errors occur.
```
qualified enum Days { A, B, C }                                                                                                                                                                 
fun days() : list<Days> { 
val ds = list(Days:A) 
ds.distinct.distinct.lastN(10).firstN(10).reverse.withAll(ds.lastN(1)).with(Days:A).without(Days:B).pick[list(1)].where(|it == Days:A|) 
}
```

Don't use generic Object type for result of collection operations

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps

Is there a reason for` model.nodesIncludingImported(RecordChangeTarget`) instead of `model.nodes(RecordChangeTarget)`? I changed it because otherwise this exception happens:
`IllegalModelAccessError: You can write model only inside write actions`

Only look at RecordChangeTarget nodes in same model in mapping script

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/behavior.mps

The original request was for implementing baseType() In ListType, but it seems to make sense to implement in CollectionType. There are two different baseType() methods, only one was implemented through inheritance.

Override baseType() in CollectionType

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/org.iets3.core.expr.genjava.simpleTypes.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.simpleTypes.rt/models/org.iets3.core.expr.genjava.simpleTypes.rt.rt.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.genjava.simpleTypes.rt/org.iets3.core.expr.genjava.simpleTypes.rt.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Insert code, which was outsourced into a helper, back into the generator for `SumOp` to remove runtime dependencies to MPS
The outsourced helper code creates dependencies to MPS in the runtime, which shall be avoided to maintain independence of MPS for the generated java code (and thus increase performance)

Insert helper code back into the SumOp-generator

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/intentions.mps

- replace only references to the original parameter
- disallow this intention for nested short lambda expressions because the **it** expression would be ambiguous
- fixes usage of **it** expression in nested lambda expressions
- let **it** parameter navigate to corresponding short lambda expression. It doesn't make sense to navigate to next Container (e.g. map) because it might refer to a different lambda expression (e.g. an outer short lambda expression)

Fix transform explicit lambdas into short lambdas

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/intentions.mps

[minor change]
Additional commit for already merged PR 543 that didn't seem to be included in the mentioned PR. 
- It is necessary to call `runManuallyWithUIUpdate` instead of `runManually` in evaluate intentions so that the new code gets evaluated

Run manually with ui update in evaluate intentions

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/org.iets3.core.expr.plugin.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This PR adds new actions to the run menu that allows changing the test execution mode (interpreter, generator) also per workspace (persisted in workspace.xml instead of model).
Reason: The original TestExecutionConfig might be changed by a user and checked into version control. Now all other user get the new preference when they check out the project.
After this change the workspace setting is preferred over the TestExecutionConfig when it is set by the user.
The combined preference should then be queried by calling`TestExecutionSettings.getExecutionModePreference` (for example in TestSuites).

Make test execution preferences overridable in workspace settings

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps

Reason: The implementation of `InvokeFunctionOperation` -> invoke() calculates the return type of the closure literal differently than the short invoke operation -> (). In fact, the calculation is wrong:
Example from base language:
Result: Object (inner lambda return type is calculated as nulltype)
```
{ => 
if (true) { 
return { => return "hi"; }.invoke(); 
} else { 
return null; 
} 
}.invoke()
```
Result: String (correct)
```
{ => 
if (true) { 
return { => return "hi"; }();
} else { 
return null; 
} 
}.invoke()
```
I've only changed the generator of the BlockExpression because this is the only case where the wrong calculation happens.

JavaGen: Invoke generated closure of BlockExpression with compact invoke function expression

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/plugin.mps

The lambda expression was shown as the child of every other node because the flag for also show was set. There was another fix in [mbeddr.core](https://github.com/mbeddr/mbeddr.core/pull/2216) to make this fix possible.
How to reproduce and check: Execute a test case with lambda expressions ([example](http://127.0.0.1:63320/node?ref=r%3Af6b93d14-1af1-4f84-a11b-cbe2d8c5efff%28test.in.expr.os.lambda%40tests%29%2F8293738266734930343)). Right click first assert statement -> Show trace and Click Expand All button. The ShortLambdaExpression shouldn't be displayed ~10 times anymore.
Screenshot from other project:

Computation trace: Don't always show LambdaExpression

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/intentions.mps

The intention is now also available in child nodes because otherwise the intention only works, for example when the cursor is placed after the second pipe (|) symbol.

Show lambda transform intentions also in child nodes

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps

The `Library` concept now implements `isImplementationArtifact` of Concept `Chunk`.
Reason: Chunks are removed in mbeddr and therefore do not show up in the generation trace of MPS (unwanted behavior). Most of the other overriding concepts of `Chunk` also implement this method.

Make Library an implementation artifact

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/actions.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/editor.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

This PR adds autocompletion support for operation expression in the core, collections and temporal language and fixes and issue with optional cell in the temporal language. 
I've changed the editors of the temporal language so that the operation context can be overriden by the optional expression (e.g. time) and also deleted when the cursor is at the end of the context. The ability to override the context was lost after a change in the optional cell in  grammar cells where we fixed a bug where side transformations where erroneously added to neighboring cells that shouldn't have a transformation (in this case a transformation to the right and **left** side of the context cell).
There are other languages that also have the problem that the alias doesn't support code completion. Please let …

Improve expression and temporal op editors

---

build.gradle

Adds the new nexus as a publishing repository to the build.gradle ([example artifact]( https://artifacts.itemis.cloud/#browse/browse:maven-mps:org%2Fiets3%2Fopensource%2Ffeature-PublishItemisCloud.2021.1.5524.62a2b07%2Fopensource-feature-PublishItemisCloud.2021.1.5524.62a2b07.zip )).

Publish to artifacts.itemis.cloud

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps

Replaces https://github.com/IETS3/iets3.opensource/pull/575 which didn't run the build
To get correct representation of expressions as string, renderReadable() must be overriden for concept.
Implement this method for 3 concepts.

bugfix: override renderReadable() where missing

---

README.md

- Contains explanation for all languages and solutions categorized by virtual packages.
- Relevant concepts are linked and can be opened with the HTTP support plugin.
- All available devkits are listed at the bottom of the page.
- Relevant KernelF documentation is linked whenever it is possible.
Note: This is the same PR as https://github.com/IETS3/iets3.opensource/pull/509 but this time as a branch instead of a fork.

Add information about project structure to readme

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/models/org.iets3.core.expr.temporal.runtime.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps

Return an optional default value that is calculated from a type constraint on the temporal literal.
This constraint has to be set when no slices are provided. Previously, the reduce method returned null and failed with a `NullPointerException`.

Temporal language: Fix NullPointer in reduce method by introducing a default constraint type

---

code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/intentions.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.plugin/models/org/iets3/core/plugin/plugin.mps

I introduce an additional method `performAdditionalEditorUpdate` in `ICanRunCheckManually` where concepts can contribute further editor updates such as displaying the test result in the error stripe.
Also the editor is updated now only once after all checks are done.
This is a big performance improvement for huge test suites such as [collections](http://127.0.0.1:63320/node?ref=r%3A2309ed17-e7b4-45b5-b25e-2c0f3ea87e8b%28test.in.expr.os.collections%40tests%29%2F7740953487930555503).

Improve IRunManuallyWithUIUpdate logic

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/structure.mps

`org.iets.core.expr.typetags.units` : implemented smart reference to the Unit concept with dimension information in the description text, so you can see the dimension information int the completion menu:

added smart reference interface to Unit concept and implemented get description text

---

build.gradle

This PR picked up the work of https://github.com/IETS3/iets3.opensource/pull/529 and rebased it onto master.
All insides could be find in the original one. 
**Sumup**
It decouples the gradle build from any Java version installed on the host machine. The defined java version is downloaded via the mps-gradle-plugin and used during execution.

build: Add JBR download via mps-gradle-plugin

---

build.gradle

- In the scope of migriting away from https://projects.itemis.de/nexus we now remove the publication to the old repository.
- Instead we now publish all artifacts to https://artifacts.itemis.cloud/
- now only new nexus is used for dependency resolution
- In addition the version of the mps-gradle-plugin was updated to the next available on the new cloud.
- mavenLocal() repo was removed from dependency resolution as a problematic one

build: replaced old itemis nexus by the new itemis cloud nexus

---

build.gradle

Merging all 20202 -> 20203 chnages.
MPS version has been additionally updated from 2020.3.4 to 2020.3.6 since platform was previously updated to that version and due to some changes in the API also iets3.os has to be built with the same version to get all the tests running.

cascading merge to align maintenance branches

---

README.md
build.gradle
projectlibraries.overrides.properties.example
projectlibraries.properties

In the past we used `setup` task to generate libraries.xml file for the MPS project and to resolve language libraries used in the project. This approach seems now to be abandoned as the libraries.xml is provided in the repo and no one needs to rewrite it with custom paths on a regular basis. The specific task for generating libraries.xml has been apparently anyway removed from the project at some time earlier. And typically when setting up the project, the user would first need to run the build which resolves the required dependencies under the location specified in the checked-in libraries.xml file. 
I suggest to clean up the project setup a bit and drop the `setup` build task entirely. Instead `resolveDependencies` task can be used separately to get JBR, MPS and language libraries …

Clean up build setup tasks

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.collections.interpreter/models/plugin.mps

After a closer look, I noticed that the PCollection check is still to restrictive.

[minor] Collections: Further reduce withAll argument  type check to instance of Collection

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/org.iets3.core.expr.tests.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/org.iets3.core.expr.toplevel.mpl
code/languages/org.iets3.opensource/languages/org.iets3.req.plugin/models/org/iets3/req/plugin/plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

This PRs includes fixes for several issues:
- exclude commented elements from the visible elements scope: [Library](http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F543569365052711055)/[TestSuite ](http://127.0.0.1:63320/node?ref=r%3Aba7faab6-2b80-43d5-8b95-0c440665312c%28org.iets3.core.expr.tests.structure%29%2F543569365052711055) IVisibleElementProvider scope has been adjusted to exclude commented elements from the result
- use real type for reduce op with weighted strategy: using weighted strategy in [ReduceOP](http://127.0.0.1:63320/node?ref=r%3Ad6904536-4de8-40ba-b54e-09fcdfe1b62a%28org.iets3.core.expr.temporal.structure%29%2F2060704857949651508) results in correct real type for the computed value
- added check for …

Merge datev-staging branch

---

build.gradle

No breaking changes in this minor release as far as I can tell ([Release notes](https://youtrack.jetbrains.com/issues/MPS?q=%23Resolved%20%20project:%20MPS%20version:%202021.2.6&_ga=2.3773168.1193796523.1669010815-2058359210.1628057624&_gl=1*1ypeka8*_ga*MjA1ODM1OTIxMC4xNjI4MDU3NjI0*_ga_9J976DJZ68*MTY2OTEyODAzMS40MzAuMC4xNjY5MTI4MDMxLjYwLjAuMA..)).

Migrate to 2021.2.6

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps

This change is needed so that the method can be overridden.

Core expr: make NumberType.setRange virtual

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.plugin/models/plugin.mps

This is necessary to avoid the error message "AWT events are not allowed inside write action".
Please let me know if there are other dialogs created through other classes than `Messages` and `JOptionPane`. I've also fixed similar issues in mbeddr.core where the dialogs made MPS completely freeze.
A site note: such modal dialog make tests fail when they are opened because they don't work in a headless environment. Maybe [top-level notifications (balloons)](https://plugins.jetbrains.com/docs/intellij/notifications.html#top-level-notifications-balloons) would be safer (and less ugly).

Open dialogs on the EDT thread

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

Paste certain expressions into an editor where an expression was expected still didn't work.
The wrong paste action was used (the one of EditorCell_Label instead of the generic node paste action).

Restore pasting in the empty expression editor

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps

This way, an extending record declaration can use a custom equality check for special cases where two record should be treated as equal (e.g., two records have the same structure but have different version numbers).

Make IRecordDeclaration equality check overridable

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps

This PR adds a new constructor to the NixSupport class that supports initialising it with a sequence of values.
Currently there is no check applied that the list might not be empty.

Extend NixSupport with a constructor supporting list values

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps

This is a very quick addendum to https://github.com/IETS3/iets3.opensource/pull/641 where I forgot to add a function to access the list of values stored in the `NixSupport` object. This PR adds the function:
```
public sequence<Object> getAll() { 
list<Object> result = new linkedlist<Object>; 
for (int i = 0; i < values.size; i++) { 
result.addLast(this.get(i)); 
} 
return result; 
}
```

Add a getter function for the NixSupport values list

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps

Error message: `Can't cast node: 4621384398004576888, concept: jetbrains.mps.lang.typesystem.structure.RuntimeErrorType to concept: org.iets3.core.expr.base.structure.Type`
The original problem is that we calculate the super type in some rules such as the ImmutableListLiteral, IfExpression etc. and then we cast the returned node (`:Type`). The implementation of the super type method for units can return nodes of type `RuntimeErrorType` that have to be handeled separately. I've checked all instances where this method or a similar method is used and opted for throwing a type system error instead of  using a safe cast (as)  and just swallowing the error message. To me, it looks safer to not calculate a type in those cases instead of returning null and have types like List<null>.
In some …

[minor] Typesystem: handle cases where computeSupertype returns an error

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps

Improved dark theme support on DataTables
- Tables `DataTable` now fully supports dark themes
- Before (light + dark): 
- Now (Darkula + High contrast, light stays the same): 
- Moved styles from inspector into dedicated stylesheet

Improve dark themes support for tables

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/models/behavior.mps

This PR makes the function `runSolver` in the Behavior of the `ISolvable` concept virtual such that it can be overwritten in dependencies.
**Known Issues**
If the function is implicitly overwritten in sub-concepts, the reflective editor must be used to add the overriding information manually. This is only required if the function should properly overwrite the `runSolver`  method from the `ISolvable`. 
_No changes are required if the two functions can be kept separate._

Make the function runSolver virtual to overwrite it where necessary

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/typesystem.mps

With this change, the type of the referenced field can be displayed in the builder with SHIFT+CTRL+P.

Add a type to the field of FieldSetter

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps

This PR adds complementary helper methods to IETS3ExprEvalHelper, so you can call the methods without the default coverage analyzer. In some cases, e.g. when invoking the other methods too often or maybe from the generator, the default (global) coverage analyzer needs too much memory and the coverage information is not even needed.

Expression eval helper methods without coverage

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.stringvalidation.runtime/models/org.iets3.core.expr.stringvalidation.runtime.runtime.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.stringvaliation@tests.mps

```
test case predecessorSuccessor [success] {                                                  
assert validate "12345"each str[3]predecessor cannot be str[1]|.ok equals true [C] [71 ms]
assert validate "12345"each str[3]successor cannot be str[5]|.ok equals true [C] [0 ms]   
assert validate "12345"each str[3]predecessor must be str[2]|.ok equals true [C] [1 ms]   
assert validate "12345"each str[3]successor must be str[4]|.ok equals true [C] [0 ms]     
}                                                                                           
```
The first two asserts failed in the past.

[minor] stringvalidator: fix cannot be/must be for predecessor/successor

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.toplevel/generator/template/org.iets3.core.expr.genjava.toplevel@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.stringvalidation/models/org.iets3.core.expr.stringvalidation.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/org.iets3.core.expr.toplevel.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This was a customer request. All three concepts used different custom cells to denote the end of the editor. I've attached some screenshots that showcase how the newly introduced end cell looks like. It is modeled after the end cell of table rows. If you are unhappy with the look (e.g. the thickness, color), please amend the commit yourself. There is also no way to show the cursor in a good way, the same way it is done for the table rows.
The vertical line gets the highlight color when it is selected:

Unify end cell of multitab, builder expression and validate string

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/editor.mps

Give the same treatment to tagged  types as done in #658 
before:
after:

Prevent tagged types from wrapping

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/structure.mps

Add ISubstructureContent interface to AbstractComponentInterface. This change fixes a warning in dependent projects.

Minor fix for ComponentInstances.

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

As pointed out in #672 , the number type equality function (`isSameAs`) was a bit too pessimistic in using the direct precision accessor for comparisons. With this PR, the comparison function uses the the `getPrecision` function instead which allows the types `number` and `number{0}` to be treated equally.

Use precision function in isSameAs on NumberType (#672)

---

build.gradle

The old plugin `co.riiid.gradle` was outdated. This PR replaces it with a [newer plugin](https://github.com/BreadMoirai/github-release-gradle-plugin) which is the same as the one used for MPS-extensions .

Repair github publication step

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/org.iets3.core.expr.typetags.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.LeastCommonSuperType@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

Ticket: https://github.com/IETS3/iets3.opensource/issues/505
The least common super type of a set of types is determined by the method:
typechecker.getSubTypingManager().leastCommonSupertypes(setOfTypes, boolStrongSubtyping)
If setOfTypes e. g. contains the three iets3 types : {StringType, BooleanType, NumberType} , the derivation of the least common super type is done wrong. It operates correctly if there are only two types (as mentioned https://github.com/IETS3/iets3.opensource/issues/505#issuecomment-889278536). So I broke the set down and called that function repeatedly until the least common type was determined.
By the way, the list of types you see above is only an example. Any types should be allowed!
Another point is that NumberTypes are only reduced to a common Numbertype (the …

505 type system improvement

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.base/models/editor.mps
code/languages/org.iets3.opensource/solutions/test.org.iets3.core.comments/models/tests@tests.mps

The transformation action applyCommentsToIDocumentable to add a comment to an IDocumentable node is improved to only be available depending on IDocumentable.isDocumentationAllowed(). Furthermore it only jumps over IEmpty nodes to reach an IDocumentable node instead of jumping as well over non-IDocumentable nodes.
- The `applyCommentsToIDocumentable` contribution menu to add comments to nodes isn't customizable in the sense, that it's not possible to deactivate it for specific concepts, though there is `IDocumentable.isDocumentationAllowed`. It's not enough to just remove the `IDocumentable` interface, because it can be applied implicitly via several other interfaces, due to the interface hierarchy.
- Further more in this case the `execute` method is executed even though `can execute` …

Fix `add comment` transformation action in auto completion

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags/models/org/iets3/core/expr/typetags/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps

If the same unit is defined in different packages, this now leads to an error. The error shows the package in which they are not aligned as well as the root.

Remove MetaUnit and refactor unit comparisons

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/org.iets3.core.expr.temporal.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.temporal@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

`TemporalLiterals` may have multiple slices with different values at different points in time. Slices with the same point in time are forbidden, because it can lead to nondeterministic behaviour. 
Thus a check is introduced to show an error on each slices point in time, if the date is a duplicate, i.e. the date is already used in another slice. The check retrieves the date literals in the slices' point in time and compares them against each other. It can handle date literals and (nested) references to constants defining a date via a date literal. 
If a point in time cannot be unwrapped to a date literal, e.g. the date literal is part of a list, then a warning is shown, that the date literal couldn't be retrieved. This indicates, that the duplicates-check  cannot be applied to this slice …

Add error check for TemporalLiterals to identify slices with duplicate date.

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.nix@tests.mps

Add Nix Support for date/ time comparisons and calculations in the interpreter
- This PR adds missing Nix Support for date/ time comparisons and calculations in the `ExprDatetimeTypesInterpreter`. Check out the added tests for the exact overview of nix supporting functionality regarding dates and times. The Java-Gen is not covering the nix support for date/ time comparisons and calculations and was not extended in this PR.
- Fixed punctuation on the `empty` keyword

Add NixSupport for date/time comparisons and calculations in the interpreter

---

code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lookup/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.math/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps

This pull request adds a completion menu for types which editors is composed of more than one cell (see the screenshot below for an example).
For composed types, like `NumberType` with a range specified, invoking the code completion on the type name doesn't show anything. 
While this is the MPS default behaviour, we think that it would be more user friendly to show the completion menu also when invoked only on the type name alone, without having to select the whole node.
| Type | Example |
| ---- | ------- |
| `BoxType` | [`box<posInt>`](http://127.0.0.1:63320/node?ref=r%3A5d61ba74-2fa4-4f6f-9f36-f36d4e99a4c5%28test.in.expr.os.mutable%40tests%29%2F9215841044171281157) | 
| `AttemptType` | [`attempt<string\|A, B>`](http://127.0.0.1:63320/node?ref=r%3A88ec7cd5-2a4a-4f67-acf4-2cc4711c1bed%28t …

editor: add replace node menu for composed types

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps

This PR only changes the editor of functions in iets3 when no argument is given.
Before:
After:

Remove ugly empty symbol in function editor

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.units.interpreter/models/org.iets3.core.expr.typetags.units.interpreter.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.plugin.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

This PR fixes https://github.com/IETS3/iets3.opensource/issues/728. In addition, the automatically set conversion specifier of the `convert` expression and the `convertTo`  target is now used instead of the first applicable conversion specifier. This way, the converting even works with those cyclic definitions. The editor also shouldn't freeze anymore when using cyclic definitions. Example:
```
quantity quantityA                                          
quantity quantityB                                          
unit a := b for quantityA
unit b := a for quantityB
unit c := c
conversion a -> b {                                         
val as <no type> -> val * 1000                              
}                                                           
conversion b -> a { …
```

Add a cycle check to the unit definition + use correct conversion specifier when converting units

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/behavior.mps

The class `IETS3ExprEvalHelper` was deprecated and a new class `IETS3ExprEvaluator` was introduced that can also influence the creation of the computation trace. The interpreter doesn't automatically create a computation trace anymore that is discarded anyway.
The performance improvements are unfortunately only minimal and are only noticeable for larger computations e.g.
`10.upto(500).map(|it: number{0} => it * 2|).where(|it >= 50|).size` now sometimes takes 125 ms instead of 130 ms.

Don't call the interpreter with computation trace enabled with it is not necessary

---

build.gradle

Before closing #741, we need to make sure the `maintenance/mps20222` branch is up-to-date with the changes applied to this version.

Merge changes from master into maintenance/mps20222

---

CHANGELOG.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- Version 4.0.1 of PCollections is backwards compatible with 4.0.1.
- I've upgraded Gradle to 8.5 to fix an issue where the JBR couldn't be extracted: `org.gradle.api.GradleException: Unable to expand TAR`

Update PCollections to 4.0.1 and Gradle 8.5

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.temporal/models/typesystem.mps

The initial creation of a [DateLiteral](http://127.0.0.1:63320/node?ref=r%3A9ec53fca-e669-4a18-ba8b-6c9f4f1cb361%28org.iets3.core.expr.datetime.structure%29%2F3885635233757569297) lead to a `DateTimeException`.
**Thrown exception**
```
DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
at java.base/java.time.LocalDate.of(LocalDate.java:269)
at org.iets3.core.expr.datetime.behavior.DateLiteral__BehaviorDescriptor.toDate_id26CArgU4p85(DateLiteral__BehaviorDescriptor.java:61)
at org.iets3.core.expr.datetime.behavior.DateLiteral__BehaviorDescriptor.invokeSpecial0(DateLiteral__BehaviorDescriptor.java:115)
at …
```

expr.temporal: improved exception handling in check

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps

There was a strange condition in the StringLengthTarget Java generator that prevented correct generation inside a block or if. I have removed this condition. Nobody seemed to remember why it was there in the first place.

Fixed the StringLengthTarget

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps

This PR  updates the reduction rule for TupleAccessExpr and adds an additional type cast in case a typesystem type is present. 
Those change prevents issue #774 from happening and avoid a compilation error.

core.expr.genjava.base: added type cast for TupleAccessExpr

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps

This change adds an intepreter for [MakeTime](http://127.0.0.1:63320/node?ref=r%3A9ec53fca-e669-4a18-ba8b-6c9f4f1cb361%28org.iets3.core.expr.datetime.structure%29%2F4274681253353315973) into the [ExprDatetimeTypesInterpreter](http://127.0.0.1:63320/node?ref=r%3A9931730f-a933-4ee8-8dad-53a254a9519e%28org.iets3.core.expr.datetime.interpreter.plugin%29%2F553080662195419964). 
fixes #702

Add interpreter for makeTime

---

CHANGELOG.md
build.gradle

At the moment our TC configuration allows the execution of the `publish` task despite of failing tests. This PR adds additional functionality to fail our build in case we have failing tests. 
We want to still execute all tests and collect their results as part of the junit result xml file. However in addition we want the build to fail in case tests are failing.  Therefore the `buildAndRunTests()` task was updated to parse the result xml file and throw an exception in case of test failures.

build.gradle: added build fail on test failure

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

When the expression in the box expression has a specific number type, a generic integer type is used instead. Fixes #170 
An example can be seen in #170. Let me know if you see any additional problems.

Improve type of box expression

---

build.gradle

All branches except main, maintenance and customer branches should go to the -SNAPSHOT branch. 
fix #823

adapt iets3.os to use snapshot repo

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/migration.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.mutable/org.iets3.core.expr.mutable.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/intentions.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/org.iets3.core.expr.statemachines.mpl

Removed not required dependencies to `httpsupport`. Those uneeded deps rose errors on customer RCPs.

mutable/statemachines: optimized imports

---

build.gradle

build.gradle: snapshot version calculation is now backwards compatible

---

code/languages/org.iets3.opensource/solutions/test.org.iets3.core.comments/models/tests@tests.mps

With the latest change in https://github.com/JetBrains/MPS-extensions/pull/805, words in the documentation are not empty anymore when they are created but also contain a character (space).

Fix failing word tests

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps

Example node where it didn't work: http://127.0.0.1:63320/node?ref=r%3Aa2594bdc-f128-474d-863a-401664a7ab8e%28test.in.expr.os.todo%40tests%29%2F5070313213711196305
There was a warning that the type never gets concrete.

Fix type calculation of field setter

---

build.gradle

BUILD_NUMBER is redefined by this build file on CI so we cannot run more than one Gradle step. BUILD_COUNTER is defined on TeamCity to be %build.counter% and is not touched by the build.

Use BUILD_COUNTER instead of BUILD_NUMBER

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.components.core/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.attributes/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.attributes/org.iets3.core.attributes.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/org.iets3.core.expr.messages.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.statemachines/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/solutions/test.org.iets3.core.comments/models/tests@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

These old steps to create a new member:
- create a record
- then you create an empty line
- then you need to create a record member if you don't know that you can just start typing (1)
- <img width="713" alt="Screenshot 2024-04-22 at 10 32 19" src="https://github.com/IETS3/iets3.opensource/assets/88385944/c01a46ae-4bdb-45af-bb7c-5a75211f2691">
- then you can set its name and data type
There is no information about (1), so people use the code completion menu to select the only applicable entry: a new member. With this PR, the only CC menu entry is automatically selected. The empty line is also inserted automatically when you create a new declaration.
The request was initially only for record declarations but I also added this feature to other concepts that represent empty placeholders like …

If there is only a single CC menu entry, select it for concepts that act as empty placeholders

---

code/languages/org.iets3.opensource/languages/org.iets3.core.base/org.iets3.core.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/generator/template/org.iets3.core.expr.genjava.temporal@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.temporal/org.iets3.core.expr.genjava.temporal.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/models/org.iets3.core.expr.temporal.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/org.iets3.core.expr.temporal.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/temporal@tests.mps

The old impl. would lead to a NPE due to in `!res.lastSlice().value().equals(ithSlice.value())` in case the value was null. Switching to a null save comparision fixes this problem.
Addition tests were added to cover the newly added functionality.

temporal.runtime: TemporalOps.joinSlices can now handle null values of slices

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.data/generator/templates/org.iets3.core.expr.genjava.data.generator.templates@generator.mps

expr.genjava.data:DataTableLookup: fixed java generation column index

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.base/org.iets3.core.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.physunits.documentation/models/org.iets3.core.expr.typetags.physunits.documentation.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.phyunits.si/models/org.iets3.core.expr.typetags.phyunits.si.units.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.plugin.mps

- small fixes related to the minimization of groups and fractions
- exponent expression now doesn't use references as the base anymore
- improvement and fixes in substitute menus
- small adaptions to the standard libraries
- improvements in the NewUnitLanguageMigrationHelper to support migrating custom libraries
- fixes https://github.com/IETS3/iets3.opensource/issues/882
There is one unintuitive case with dimensions that I read about: If I define `unit specialUnit = °/m for unspecified quantity`, the dimension is calculated based on the quantity and therefore 1 and not 1/L.

[Breaking] Bugfixes and improvements for new unit language

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.temporal.runtime/models/org.iets3.core.expr.temporal.runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.physunits.documentation/models/org.iets3.core.expr.typetags.physunits.documentation.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.phyunits.si/models/org.iets3.core.expr.typetags.phyunits.si.units.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps

- implement transformation properties for quantities (scalar, vector, tensor..), add them to the standard library + improve the standard library (fixes https://github.com/IETS3/iets3.opensource/issues/945)
- prevent precision loss in the interpreter
- undo the change of the binary prefixes; the old prefixes were indeed correct. I also renamed the units for bytes and bits to better reflect the names you would see in the wild.
- improve the binary units and implement a new binary prefix for memory purposes (fixes https://github.com/IETS3/iets3.opensource/issues/944)

physunits: implement transformation properties, prevent precision loss in the interpreter + improve binary units (memory prefix)

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps

The space between the range and, for example, the name of variables was missing + the side transformations for the precision didn't work.

Remove the incorrect punctuation-right from NumberRangeSpec

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.functions@tests.mps

Generator: Added tests producing invalid java code (#956).

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/editor.mps

We have to look carefully if it is indeed not needed or otherwise other editors will break. What happened is that the last entry of a collection was not selectable with the mouse because the end cell was visible in the editor and forced layout changes because of the` push-y` attribute.

Remove push-y from EndCell

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

There are some rare cases, where MPS duplicates the transformation menu because it creates two default transformation menus. When we have an explicit transformation menu. I am not sure if we need to include the super concepts menu here like in the automatically generated one but it doesn't seem to hurt.

Force a empty default completion menu (including the super concepts menu) for IDotTarget

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

- follow up of #984 
This change is necessary so that the menu also works for derived interfaces/concepts. It didn't work for the following case: `concept C` implements `I`, `interface I implements IDotTarget`.

Force a empty default completion menu (including the base concepts menu) for IDotTarget

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps

The parent side transformation entries were included for some reason which duplicates some entries. I really don't understand why this was necessary in the first place (and only for the right side). I feel like this was a workaround for an old (fixed) issue. For the new unit language, for example, we do it on purpose but here it doesn't make sense.

IDotTarget: Fix duplicate right side transformation entries

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.interpreter/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.tuples@tests.mps

The use case is long initializers with the same values such as initializing a tuple with zeros.                                                                                                      
Example: `assert [1, 2].nTimes(3) equals [1, 2, 1, 2, 1, 2]`

Implement an ncopies operation for tuples to ease initialization

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tracing/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tracing/org.iets3.core.expr.tracing.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/org.iets3.core.expr.tracing.plugin.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This Ticket addresses: https://github.com/JetBrains/MPS-extensions/issues/855
A ConditionalEditor by default has the hints `conditionalEditor` and `conditionalEditor_doNotUseThisHint`. These hints are enabled by default when the plugin becomes initialized.
If someone wants to overload a conditionalEditor it is not enough to just give it a higher priority. The priority just defines the order of the applied editors (a conditionalEditor uses [NextEditor]) see http://127.0.0.1:63320/node?ref=r%3A8d20232d-87e2-425b-b4d7-a9790e401b85%28de.slisson.mps.conditionalEditor.structure%29%2F2877762237607058140)" (s. screenshot on the mps-extension ticket above). So these can be cascaded somehow.
To enable overloading:
Generally an implementation of a conditional editor should also get an new defined …

 Enable override of Tracing editor

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.tuples@tests.mps

For example _[[1, 2], [3, 4]].nTimes(20)_ completely froze MPS. I don't know if the order of the when concrete block was the issue or inefficient list operations.

expr.base: rewrite NCopies rule to avoid freezes for large numbers

---

build.gradle

Incorporation of license info in POMs for 
- org.iets3.core.expr.base.shared.runtime
- org.iets3.core.expr.simpleTypes.runtime
- org.iets3.core.expr.datetime.runtime
- org.iets3.core.expr.temporal.runtime

Added license info to runtime library POMs

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps

addresses issue: #1032 
This PR is required to get the changes (for the TraceExplorer) in mps20223 versions and upwards.
(These were cherry picked from datev-loon-staging-20222)

TraceExplorer: weakens too restricted interface again (#1032)

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.constraints.mps

The access to the repository was not safe for the generator, so we have to hard-code the name.

physunits: make the unitless unit name customizable (followup)

---

build.gradle

The initial dynamic version `2022.2.3+` was always resulting in this mps-qa version: `2022.2.399.d6e4c4b`. 
This is now fixed.

gradle: fixed mps-qa version

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.data/models/org.iets3.core.expr.genjava.data.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.data/org.iets3.core.expr.genjava.data.mpl

Without the devkit corresponding checkpoints are not produced, making it impossible to override typesystem rules of the language.

Use the typesystem devkit in typesystem models

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.tracing.plugin/models/org.iets3.core.expr.tracing.plugin.plugin.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.phyunits.si/models/org.iets3.core.expr.typetags.phyunits.si.units.mps
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.linters/models/org.iets3.opensource.linters.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps

Some users really don't like seeing, for example, 10 m²÷s instead of 10 m²/s. The other special characters seem to be fine. For generation purposes, they can be replaced by calling `UnitNameReplacementHelper#replaceUnitName`.

physunits: make it possible to replace ÷ automatically with /

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.data/models/org.iets3.core.expr.data.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.tests/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.util/models/editor.mps

We still had usages of deprecated links of the table edtitor cell. Those editors are now re-written. 
Editors re-written for: 
- DecTab
- DataTable
- AbstractVectorCollection
- IMultiDecTab
Fixes #1064

Refactored Table Editors

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps

Using a list with a strict bound makes it impossible to pass a list of subconcepts to the method. This error is new in MPS 2023.2.

UnitConversionUtil#createUnitMultiplication: use sequence instead of list

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.base/generator/template/org.iets3.core.expr.genjava.base@generator.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.dectabs@tests.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.tuples@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

Tuple types where all elements have the same type can now be used interchangeable with list types. Here is a concrete example where `nTimes` returns a tuple but the result is assigned to a list:
On the generator level this level should also be fine as both tuples and lists use the class `PVector`. I just had to use `PVector` instead of `PVector<Object>` in some places.

add a replacement rule for homogeneous tuples and lists

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.adt/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/intentions.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.collections/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.datetime/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.genjava.simpleTypes/generator/template/org.iets3.core.expr.genjava.simpleTypes@generator.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.messages/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.repl/models/org/iets3/core/expr/repl/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/org/iets3/core/expr/toplevel/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.lib/models/org/iets3/core/expr/typetags/lib/typesystem.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.LeastCommonSuperType@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps

This PR enables adding a regular expression to string types using the built-in regexp language + some extensions in [MPS-Extensions](https://github.com/JetBrains/MPS-extensions/pull/994) to enable most of the features of the [Java regex language]([docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html)).
You can add the constraint manually when you use the string type or add the constraint dynamically when calculation a type. When one string type has a constant text constraint it can be matched against the constraint of another string type (see implementation of string literal type).
One implementation note: a removed the support for parenthesis in those regexes and added …

New String type with constraints

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/org.iets3.core.expr.typetags.units.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/models/typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.units/org.iets3.core.expr.typetags.units.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/org.iets3.core.expr.base.runtime.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/unitsonly@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

- For units to be compatible, they need to have the same quantity and an (implicit) conversion must exist between them.
- Quantity types are also not allowed in tagged types anymore. That doesn't make sense at all. I think we should also discuss the feature that you can use quantities as tagged types such as 1 force + 2 force in a followup ticket. It looks ridiculous to me.

physunits: check compatibility of units with same quantities

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/org.iets3.core.expr.typetags.physunits.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps

- Type calculation for implicit conversions in the physunit language was improved.
- Implicit conversions can now be deactivated conditionally in the physunit language. You can for example, only activate them for binary operations, so that normal assignments like val length: number<m> = 1 km still leads to errors
- The `noConvert` expressions in the physunit language doesn't strip the unit anymore. Use the `stripUnit` expression for that. 
I also have to fix the type calculation for div expressions since they contained unnecessary trailing zeros which leads to ugly number ranges with those implicit conversions. The changes for the type calculation were also done for the `convertTo` expression.
Implementation details: The reason why we need to widen the precision in the tagged expression …

physunits: improve implicit conversions

---

build.gradle
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.datetime.runtime/models/org.iets3.core.expr.datetime.runtime.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/datetime@tests.mps

The [endComparison](http://127.0.0.1:63320/node?ref=r%3Aa9ac3767-b241-4aa4-a973-d04bb5ce184c%28org.iets3.core.expr.datetime.runtime%29%2F7492452870508394462) was using wrong value. 
In addition I've also bumped up the MPS version to 2022.2.**4**

datetime.runtime: Fixed compareTo in ArbitraryDateRangeValue

---

code/languages/org.iets3.opensource/languages/org.iets3.analysis.base/org.iets3.analysis.base.mpl
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/behavior.mps
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.nix@tests.mps

Updating HasValue_OP to not propogate optional type to dot expression
When HasValue_OP was being used on a expression tyoe that was an optional, the resulting type of the dot expression also became an optional -this can be seen in the below screenshot
This made it difficult to work with since you had provide x.hashValue :? false etc everywhere
By checking the DotExpression Type system aspect i could see reference to the dot expression method neverMakeOption, which default to false but for this case HasValue presumably should be true.
I added sometests within the existing test suite

Updating HasValue_OP to not propogate optional type to dot expression

---

code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.math.interpreter/org.iets3.core.expr.math.interpreter.msd
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

For solution `org.iets3.core.expr.math.interpreter`, both the `models` and the `lib` folder were registered as model roots.
However, `lib` doesn't contain any models, which lead to model loading warnings on every MPS startup.

removed math.interpreter lib folder as model folder

---

code/languages/org.iets3.opensource/.mps/modules.xml
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.toplevel/models/intentions.mps
code/languages/org.iets3.opensource/languages/test.ts.expr.os.nix/models/test.ts.expr.os.nix.editor.mps
code/languages/org.iets3.opensource/languages/test.ts.expr.os.nix/models/test.ts.expr.os.nix.structure.mps
code/languages/org.iets3.opensource/languages/test.ts.expr.os.nix/models/test.ts.expr.os.nix.typesystem.mps
code/languages/org.iets3.opensource/languages/test.ts.expr.os.nix/test.ts.expr.os.nix.mpl
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.LeastCommonSuperType@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

This used to work in previous versions of iets3.opensource (at least 2023.2.7319.4e501a1), but not currently.
I added all these tests (and an test language with a nix type).
The goal is to remove `NixType` from _xxx_ in `ListType<xxx>`.
```
Lists with nix                                                                        
------------------------------                                                        
val oneNix = <check list(nix) has type list<nix type>[1|1]>                           
val twoNix = <check list(nix, nix) has type list<nix type>[2|2]>                      
val stringFirst = <check list("hello", nix) has type list<string>[2|2]>               
val nixFirst = <check list(nix, "hello") has type list<string>[2|2]>                  
val stringFirstThree = <check …
```

Reliably remove NixType from ListType

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps

This workaround is necessary for cases where projects can't switch to implicit conversions.

physunits: allow mixing quantities with different prefixes through IUnitLangConfig#implicitConversionIsEnabledAt

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.structure.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.typetags.physunits/models/org.iets3.core.expr.typetags.physunits.typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.typetags.phyunits.si/models/org.iets3.core.expr.typetags.phyunits.si.units.mps
code/languages/org.iets3.opensource/solutions/test.org.iets3.analysis.base/test.org.iets3.analysis.base.msd
code/languages/org.iets3.opensource/tests/test.in.expr.os/models/test.in.expr.os.coverage@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.phyunits@tests.mps

- The physical units B and b were renamed to byte and bit to avoid confusion.
- Breaking change: The units of digital information were split into 3 different libraries: `UnitsOfInformationIEC`, `UnitsOfInformationJEDEC`, `UnitsOfInformationMetric`. They are still considered part of the derived units. If you want to use them, you therefore have to include them in your scope method.
- Physical units now also support metric scaling for only the positive and negative prefixes.
- I also noticed that many derived units can also have metric prefixes. The information for the last and this item are AI checked, so we have to trust the information that we got.
-  Scaling can also be overwritten for units by overwritten `IUnitLangConfig#getOverwrittenScaling` for the extension point …

physunits: Improvements to units of digital information

---

code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/behavior.mps

Looked like a cast went side ways. I've changed the target type to the correct one.

expr.lambda: fixed cast

---

code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

This solves #1292. The missing test language `o.i.core.trace.test` is deployed now in the `org.iets3.core.trace.test` plugin.
Questions for the reviewers:
- Why do we deploy the test solutions at all? 
- Could it be a problem if we now deploy an additional language for the tests?

Add language o.i.core.trace.test to deployed languages

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/plugin.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.LeastCommonSuperType@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.base@tests.mps

- When calculating the super type of number types, the precision is now correctly set to infinite when one of the types has an infinite precision.
- fixes #1004

expr.simpleTypes: use infinite precision if any of the number types in the supertype calculation has an infinite precision

---

CHANGELOG.md
code/languages/org.iets3.opensource/solutions/org.iets3.opensource.build/models/org/iets3/opensource/build/build.mps

Rename plugin org.iets3.safety because this name collides with a plugin with same name in core (#1318)

1318: Rename plugin org.iets3.safety to org.iets3.safety.os

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.base/models/plugin.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/constraints.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/editor.mps
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.simpleTypes/models/typesystem.mps
code/languages/org.iets3.opensource/solutions/org.iets3.core.expr.base.runtime/models/runtime.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test.ts.expr.os.plugin.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/models/test/ts/expr/os/m1@tests.mps
code/languages/org.iets3.opensource/tests/test.ts.expr.os/test.ts.expr.os.msd

The primitiveTypeMapper extension supports a new method, `PrimitiveTypeMapper#useStringConstraints, ` which can be set to false to disable string types with constraints and go back to regular string types. The default implementation activates the string constraints, so we don't have another breaking change. Fixes https://github.com/IETS3/iets3.opensource/issues/1182

core.expr: Make it possible to deactivate string constraints through the PrimitiveTypeMapper extension point

---

.gitignore
CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.core.expr.lambda/models/plugin.mps

This PR fixes the issue in #1397. The affected node is [ShortLambdaValue](http://127.0.0.1:63320/node?ref=r%3A51edfe99-0380-475c-a3e9-1d4425eac12f%28org.iets3.core.expr.lambda.plugin%29%2F3734061327537604455).
This change is only logically and makes sure that shorlabmda expressions are always updated. If this is not done, old values are caches and issues such as #1397 arise.
Fixes #1397
Todo:

Fix shortlambda caching bug

---

CHANGELOG.md
code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.base/models/org.iets3.variability.artifacts.base.behavior.mps
code/languages/org.iets3.opensource/languages/org.iets3.variability.artifacts.base/models/org.iets3.variability.artifacts.base.plugin.mps

This PR provides some extensions to the Filtering&Instantiation functionality of the variability framework. It mainly extends the configuration options for the filtering algorithm. This is required for extensions of the algorithm implementation in IETS3-Core (see ticket [1605](https://github.com/IETS3/iets3.core/issues/1605) in IETS3-Core). 
For details about the changes see #1407. The changes should be backwards compatible, no migrations were introduced.
Note: We are about to split the variability test-suite in IETS3-Core and migrate the base-related tests to IETS3-OS. After this is done, we will build tests also for the kind of extensions provided in this PR.
This solves #1407.

Extensions for the configuration API of the variability filtering framework
